### ISSUE TITLE
Connection timed out and "ECONNRESET" error

### ISSUE THREAD

**Issue by jchittoda** [NomicFoundation/hardhat#1124]
When running tests with hardhat, it keeps slowing down the test execution and after some time the connection is lost from the HRE and we get the below error:

```Error: Returned error: request to http://localhost:8545/ failed, reason: connect ECONNRESET 127.0.0.1:8545```

Just before it shows the timeout error, we observed approx 6000+ calls to `eth_getBlockByNumber` on HRE console. This connection error issue is intermittent. Usually, it gets triggered during execution of `BErc20.spec.ts` test file.

Following are the commands to reproduce this issue:
```
git clone https://github.com/backstop-protocol/BCompound.git
cd BCompound
git checkout hardhat-issue
git submodule update --init --recursive
npm i
npx hardhat compile
npx hardhat typechain
npx hardhat node (1st window)
npx hardhat test (2nd window)
```

**Comment by JoeBlack220** [comment]
I observed similar issues here. The test case is not failing every time, but the chances of failing are much higher than the succeeding.

**Comment by fvictorio** [comment]
Hi, I'm going over old issues to check if they are actionable. We've changed a lot how we do our http requests since this one was opened. Also, I think the reproduction branch doesn't work anymore. So I'm going to tentatively close this. If someone is running into a similar issue and has reproduction steps, please open a new issue.
