### ISSUE TITLE
Waffle's calledOnContractWith is not supported by Hardhat

### ISSUE THREAD

**Issue by imkrish** [NomicFoundation/hardhat#1135]
According to the waffle document:
https://ethereum-waffle.readthedocs.io/en/latest/matchers.html

There is a very useful matcher for testing if a function with certain arguments was called on the provided contract:

**calledOnContract**
**calledOnContractWith**

I tried to use it in my waffle project but got this error message when running the test.
`AssertionError: Waffle's calledOnContractWith is not supported by Hardhat`

Would be awesome if hardhat supports this.

Thanks a lot

**Comment by sisco0** [comment]
# The three steps journey to solve this issue

I am happy to contribute to this issue with the results of my investigation in order to aid the development of this wonderful project. As it was pointed out by @imkrish by here and our _Discord_ channel there seems to be some lack that could be tackled in order to improve _HardHat_.

The tests linked to this issue are these:
https://github.com/nomiclabs/hardhat/blob/974362a5f7af53b9c1b1617f708da40c5b422f39/packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/tests.js#L15-L39

These tests return correct results, taking into account the exception thrown by the methods below:
https://github.com/nomiclabs/hardhat/blob/974362a5f7af53b9c1b1617f708da40c5b422f39/packages/hardhat-waffle/src/waffle-chai.ts#L64-L80

Of course these methods **could be properly included in HardHat** by adding to the `packages/hardhat-waffle/src/waffle-chai.ts` file (the one which extract has been shown above). In order to do so there are thre steps to accomplish:

## First step: Add the `require` and delete the throwers

The function definitions above should be deleted and the corresponding requires should be used for each one of these methods:

```typescript
const { supportCalledOnContract } = require(`${waffleChaiPath}/matchers/calledOnContract/calledOnContract`);
const { supportCalledOnContractWith } = require(`${waffleChaiPath}/matchers/calledOnContract/calledOnContractWith`);
```

## Second step: Add `history` to the provider used

My investigations led to understand why this has been taken out of the _Hardhat_ routes. It seems that a `history` getter should be embedded under the mock provider used. This could be seen at the `waffle-chai` repository, particularly at https://github.com/EthWorks/Waffle/blob/8c5942d326c43673257f02e92c37b45c6d2d3ec1/waffle-chai/src/matchers/calledOnContract/calledOnContractValidators.ts#L13-L17 where the validation takes place, a `callHistory` method should be present at the mock provider used. At the `waffle-chai` tests this is accomplished by using `MockProvider` from `@ethereum-waffle/provider` as shown in https://github.com/EthWorks/Waffle/blob/8c5942d326c43673257f02e92c37b45c6d2d3ec1/waffle-chai/test/matchers/calledOnContract/calledOnContractWith.test.ts#L1.

This could be accomplished at our project by adding to our mock provider used something similar to what is found at https://github.com/EthWorks/Waffle/blob/8c5942d326c43673257f02e92c37b45c6d2d3ec1/waffle-provider/src/MockProvider.ts and https://github.com/EthWorks/Waffle/blob/8c5942d326c43673257f02e92c37b45c6d2d3ec1/waffle-provider/src/CallHistory.ts.

## Third and last step: Modify tests (maybe the first step for the TDD people)
Tests present below should be modified in order to accomplish the expected task to be accomplished. 
https://github.com/nomiclabs/hardhat/blob/974362a5f7af53b9c1b1617f708da40c5b422f39/packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/tests.js#L15-L39

**Comment by doylio** [comment]
This feature would be amazing!!  Any update on this?  Happy to pitch in if someone points me where to go

**Comment by sebastiantf** [comment]
Would love to have this

**Comment by jurajpiar** [comment]
Any update on this?

**Comment by fvictorio** [comment]
Closing this in favor of #3234.
