### ISSUE TITLE
Not possible to set max value of config.solidity.settings.optimizer.runs

### ISSUE THREAD

**Issue by 852Kerfunkle** [NomicFoundation/hardhat#1589]
According to this Solidity blog post: https://blog.soliditylang.org/2020/11/04/solidity-ama-1-recap/

The maximum possible value for --optimize-runs is 2**64-1.

Hardhat only allows 2**32-1, anything larger than that will result in this error:

```
The "runs" setting must be an unsigned number.
Error HH600: Compilation failed
```

It's a minor issue, setting such a high number of runs surely is unreasonable.

**Comment by cameel** [comment]
The blog post states that the limit is `2**64-1` and it's true in that the compiler internally stores this value in a variable of type [`size_t`](https://en.cppreference.com/w/cpp/types/size_t) which has the size of 64 bits on 64-bit platforms.

But the situation is oddly complicated due to platform-specific nature of types in C++:
- On 32-bit plaforms `size_t` has the size of 32 bits.
- The input validations enforce a lower limit anyway so you won't be able to set it to that theoretical maximum:
    - In Standard JSON it's always `2**32-1` (because of `Uint` type).
    - On the command line it's `2**32-1` but could technically also be `2**16-1` (because it's [`unsigned`](https://en.cppreference.com/w/cpp/language/types)).
- Coincidentally, I have just recently done a refactor that makes the type consistent and would actually raise the limit to `2**64-1` (still platform-specific though). https://github.com/ethereum/solidity/pull/11550

All in all, given that the values beyond `2**32-1` are unlikely to be useful in practice, sticking to that limit in Hardhat seems reasonable to me for the time being.

Perhaps we should just sort it out in the compiler and switch to a platform-independent type like `uint64_t`. I suspect that there are many other values affected by this though.

**Comment by 852Kerfunkle** [comment]
> Perhaps we should just sort it out in the compiler and switch to a platform-independent type like uint64_t.

It is good practice to avoid use of size_t where possible.

**Comment by 852Kerfunkle** [comment]
> Perhaps we should just sort it out in the compiler and switch to a platform-independent type like `uint64_t`. I suspect that there are many other options affected by this though.

It is good practice to avoid use of size_t where possible.

**Comment by cameel** [comment]
I mean, it's perfectly fine for stuff that actually stores a size of an object and this happens a lot. But yeah, for stuff that's exposed to the outside a platform-independent type should be used.

**Comment by 852Kerfunkle** [comment]
Yes, valid uses for `size_t` are when dealing with memory allocations, arrays, sizes of objects in memory, and some other things.

**Comment by fvictorio** [comment]
It seems then that the correct thing to do here is to keep the current limit of `2**32-1` but to show a better error message.

**Comment by cameel** [comment]
Yeah. By the way, I restored the original `2**32-1` limit for the CLI in my refactor to keep things consistent.

I see that this is the only numeric argument we have in the CLI after all so think I'll do another refactor to change it to `uint32_t` which will keep the limit the same on all platforms.

**Comment by 852Kerfunkle** [comment]
Awesome, thanks!

By the way, I have done some experimenting on my contracts anything higher than around 200k runs, the generated bytecode stays more or less the same.

In my case, so to be taken with a grain of salt.

**Comment by fvictorio** [comment]
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/3488.
