### ISSUE TITLE
Add a warning for importing ethers into files

### ISSUE THREAD

**Issue by vancedy** [NomicFoundation/hardhat#1691]
A clear warning should be added to the hardhat documentation that reminds the user to not import "ethers" as it can cause many problems when imported outside of the global scope.

**Comment by alcuadrado** [comment]
Hey @vancedy105,

Can you elaborate on this please?

**Comment by fvictorio** [comment]
I guess they mean that you should use the `ethers` instance in the HRE instead of doing `import ethers from "ethers"`? If that's the case, I agree this is something we should include in the `hardhat-ethers` docs.

I would add in two places: where the injected `ethers` object is first mentioned (use this, not the one imported) and a troubleshooting section ("if a helper like getContractFactory doesn't exist, it might mean that you are importing ethers directly").

**Comment by vancedy105** [comment]
Yes, this is what I meant @fvictorio. The issue can be that VScode can and does automatically put `import ethers from 'ethers'` when using ethers from what I've seen most commonly but generally I think importing ethers manually causes a lot of things to break if using hardhat.

**Comment by feuGeneA** [comment]
Idea: consider a troubleshooting section that quotes the error message.

Idea: expand the environment extensions section with this warning.

**Comment by fvictorio** [comment]
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/3487
