### ISSUE TITLE
Incorrect behaviour when listening to contract events: when refresh the page, listener get called for past events

### ISSUE THREAD

**Issue by StErMi** [NomicFoundation/hardhat#1773]
Hi there,

I think that there's a bug on event listening with the local hardhat network. I've tested it deploying on rinkeby with alchemy and it seems to work as expected.

Expected

I listen to an event and I only get NEW events.
If I refresh the page the listener should not give me past events.

Current behavior:

When I refresh the page, the listener get triggered with past events

Contract on Rinkeby: https://rinkeby.etherscan.io/address/0xcf4111362047bca0ad7e0c584b878d79c98cea04#code
Contract code

```
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/access/Ownable.sol";

contract TestEventContract is Ownable {
    event TestEvent(string paramString, uint256 timestamp);

    constructor() {
        // do nothing
    }

    function raiseEvent(string memory paramString) public {
        emit TestEvent(paramString, block.timestamp);
    }
}
```

React code to listen to events (it's a hook)

```
import {JsonRpcSigner, Web3Provider} from '@ethersproject/providers';
import {ethers} from 'ethers';
import {useEffect} from 'react';

import {TestEventContract__factory} from '../typechain/factories/TestEventContract__factory';

const getTestEventContract = (withSigner = false) => {
  const contractAddress = '0xCf4111362047bCa0AD7e0C584B878D79C98cEa04';
  const provider: Web3Provider = new ethers.providers.Web3Provider((window as any).ethereum);
  const signer: JsonRpcSigner | Web3Provider = withSigner ? provider.getSigner() : provider;
  const contract = TestEventContract__factory.connect(contractAddress, signer);
  return contract;
};

const useListenToEvents = () => {
  useEffect(() => {
    console.log(`useListenToEvents useEffect enter`);
    const contract = getTestEventContract();

    const filter = contract.filters.TestEvent();
    const listener = (event: any) => {
      console.log(`useListenToEvents new event`);
      console.log(event);
    };

    contract.on(filter, listener);

    return () => {
      console.log(`useListenToEvents useEffect exit`);
      contract.removeListener(filter, listener);
    };
  }, []);

  // return newRegin;
};

export {useListenToEvents};
```

**Comment by StErMi** [comment]
@fvictorio do you need something else to reproduce the problem?

**Comment by fvictorio** [comment]
@StErMi, no, thank you. I think I also noticed this. We are working on something that might fix this.

**Comment by abusomani** [comment]
@fvictorio Were you able to resolve the issue? What was the fix?

**Comment by sveitser** [comment]
I'm not sure this is the same issue but it may be related. We ran into an issue where hardhat always returns events from the last block because `fromBlock` is set to the latest block number if `fromBlock` is greater than the latest block number and `fromBlock` is inclusive.

https://github.com/NomicFoundation/hardhat/blob/4d43cbbebdb2ced843a29fa12b895d4fe5f01e83/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L2392-L2393

With go-ethereum setting a `fromBlock` greater than the latest block number does not return any events.

**Comment by vincanger** [comment]
@StErMi I solved this while testing against the hardhat node on localhost (code below) but I'm curious if this would cause problems in production?

```TypeScript
  useEffect(() => {
    const getBlockNumber = async () => setPrevBlockNumber(await provider.getBlockNumber());
    getBlockNumber();
    
    //...
    
    const transferHandler = async (amount, emittedEvent) => {
      if (emittedEvent.blockNumber > prevBlockNumber) {
         //... do stuff
      }
      setPrevBlockNumber(emittedEvent.blockNumber);
    }

    tokenContract.contract.on(TokenEvent.Transfer, transferHandler);

    return () => {
      tokenContract.contract.off(TokenEvent.Transfer, transferHandler);
    }
  }, []);
```

**Comment by fvictorio** [comment]
The issue here is that when you start listening for events, the latest block is immediately checked. If you are using the Hardhat network and no block was mined since the transaction that emitted the vent was sent, then the listener will be triggered again. This is just the way ethers works (check [this comment](https://github.com/ethers-io/ethers.js/issues/386#issuecomment-451025717)).

Possible solutions:
- Mine a new empty block using the [`mine`](https://hardhat.org/hardhat-network-helpers/docs/reference#mining-blocks) helper.
- Enable [interval mining](https://hardhat.org/hardhat-network/docs/reference#mining-modes) so that new blocks are periodically mined.
