### ISSUE TITLE
docs: inconsistent typescript usage in "Hardhat network methods"

### ISSUE THREAD

**Issue by jrfrantz** [NomicFoundation/hardhat#1786]
In [the docs](https://hardhat.org/hardhat-network/reference/#hardhat-network-methods), there are inconsistent ways of making calls to the hardhat network -- sometimes using typescript `hre.network.provider.request` and other times using regular javascript `network.provider.send`. I think the hre prefix is a typescript thing.

A fix could be either to make them consistent or just clarify that one is using typescript and the other isn't

<img width="799" alt="Screen Shot 2021-08-11 at 1 18 56 PM" src="https://user-images.githubusercontent.com/2431257/129074260-42ef9fb1-d101-41a5-87b0-cadbb778f942.png">

**Comment by fvictorio** [comment]
Thanks for the feedback @jrfrantz, this is something we've talked about before so it's useful to know that it can bug people.

I'm personally inclined to always use `hre`, because I feel docs should err on the side of being explicit. But, on the other hand, that wouldn't reflect actual usage, since I think most (javascript) users just use the globally injected values.

Maybe what you suggested makes sense: use `hre` only for the typescript sections, even if it technically can be used in javascript too.

**Comment by jrfrantz** [comment]
Will defer to you but share my perspective in case helpful: 
I learned to program web3 apps IN hardhat (via the hackathon-boilerplate tutorial), so I didn't come in knowing about concepts like setting up a local node, or how to use ethers.js. 

As a result I didn't realize until my second project that I had previously been using hre.ethers in javascript, which wasn't quite the same as the ethers.js that I could install with npm. It was only then that I understood why sometimes the tutorial had me using hre.network.provider vs the ethers.js tutorial had me creating a new provider by connecting to alchemy via URL. Maybe using hre everywhere would have clarified (or maybe it's more complication than it's worth).

**Comment by fvictorio** [comment]
That's extremely useful, thanks @jrfrantz!

**Comment by fvictorio** [comment]
I think this is no longer relevant because now we try to only use our [network helpers](https://hardhat.org/hardhat-network-helpers/docs/overview) in the docs. Please comment if you disagree.
