### ISSUE TITLE
Can't download solidity 0.5.17

### ISSUE THREAD

**Issue by alexandrewolff** [NomicFoundation/hardhat#2125]
**Steps to reproduce**

- MacOs 10.13 high sierra, node 16.13.0, npm 8.1.0
- On a fresh hardhat project, set Greeter contract and config to solidity 0.5.17
- Get Error "HH500: Solidity version 0.5.17 is invalid or hasn't been released yet." on compilation
- I tried npx hardhat clean --global but didn't fix it

**Comment by morgansliman** [comment]
Hi @alexandrewolff - unfortunately I'm having trouble reproducing this. I'm thinking it's probably just an internet connectivity issue on your end, but @alcuadrado can you try these steps when you have some time to see if maybe it's an OSX-specific issue?

**Comment by alexandrewolff** [comment]
Yes from my researches it seems like it is related to the OSX version. I didn't have the issue with catalina 10.15 but now have it again with monterey 12.1.

**Comment by alex-cardstack** [comment]
This issue seems to be an issue on M1 macs.

On the M1, hardhat tries to download the wasm build by looking at this json:
https://binaries.soliditylang.org/wasm/list.json

Unfortunately, for some reason there is no wasm build of solidity for 0.5.17

This issue seems to be being tracked in the solidity project here:
https://github.com/ethereum/solidity/issues/10329

I eventually managed to get 0.5.17 working. I'm not sure if it was installing rosetta, downgrading to node 14, or some other thing I tried.

0.5.16 according to the changelog is pretty much the same so you could use that version for now.

**Comment by alex-cardstack** [comment]
According to [this issue](https://github.com/ethereum/solidity/issues/12291) you can use homebrew to build native arm binaries on mac.

Then I think think you can point hardhat to use it [like this](https://github.com/fvictorio/hardhat-examples/blob/1c5c9c2a07610acc430d213b0fd3f9f0cc3bfba6/custom-solc/hardhat.config.js), and it will probably be faster than the wasm version anyway

**Comment by alcuadrado** [comment]
A small clarification: this issue is only present if you don't have Rosetta installed. Please, if you are having problems, please [install Rosetta](https://support.apple.com/en-us/HT211861).
