### ISSUE TITLE
to.be.revertedWith fails for messages having same prefixes

### ISSUE THREAD

**Issue by akshatdev0** [NomicFoundation/hardhat#2234]
For a contract below:
```
pragma solidity >=0.8.4;

contract Matchers {
    function doRevert() public pure {
        revert("Revert cause");
    }
}
```

Write hardhat test as below:
```
describe('Matchers: revertedWith', () => {
  // Test setup
  // ....

  it('Message starting with same prefixes: Should have FAILED, but PASSES', async () => {
    await expect(matchers.doRevert()).to.be.revertedWith('R');
    await expect(matchers.doRevert()).to.be.revertedWith('Re');
    await expect(matchers.doRevert()).to.be.revertedWith('Rev');
    await expect(matchers.doRevert()).to.be.revertedWith('Reve');
    await expect(matchers.doRevert()).to.be.revertedWith('Rever');
    await expect(matchers.doRevert()).to.be.revertedWith('Revert caus');
  });
});
```

All these should have `FAILED` but `PASSED`.

To reproduce, follow the steps in the README of this repo below:
https://github.com/akshatdev0/hardhat-chai-reverted-with-bug

This is not reproducible in [ethereum-waffle](https://github.com/EthWorks/Waffle), everything works as expected, as checked with the below repo:
https://github.com/akshatdev0/ethereum-waffle-reverted-with

**Comment by teddav** [comment]
Good catch @akshatdev0 
Actually it's worse than that, it seems like `revertedWith` checks for the string you pass as argument anywhere in the revert message.  
We decided to change our revert messages to numbers to save on contract size (not such a good idea, but this is a different matter...). So the problem is:

If I'm checking for revert error code "0" (which we use for 0 addresses checks), but the actual reverse code is 110, then the test is gonna pass, which makes my tests not reliable.

Here is a full example just to be clear:
```
contract MyContract {
  function willRevert(uint256 _i) public {
    require(_i > 10, "10");
  }
}
```

```
describe("Test", () => {
  it("willRevert", async () => {
    await expect(myContract.willRevert(3)).to.be.revertedWith('0');
  })
})
```
This test will pass even though the reverted message is "10"

**Comment by akshatdev0** [comment]
Yeah, devs will need to be careful around this issue while writing tests from now on until it is fixed.

**Comment by pofulu** [comment]
Based on what @akshatdev0  said, here are some examples:

If reverted message is
```
VM Exception while processing transaction: reverted with reason string 'Mint not open'
```
When I check `.revertedWith('hi')`, it will pass! Because the `hi` is `.included` in above message:
```
VM Exception w"hi"le processing transaction: reverted with reason string 'Mint not open'
               ^^
```

My temporary solution is to wrap my reason string with whole sentence:

```ts
// This test should failed properly
await expect(tx).revertedWith(revertReason('hi'))

function revertReason(reason: string) {
  return `VM Exception while processing transaction: reverted with reason string '${reason}'`
}
```

I think it's this code that is causing the bug:
<img width="1472" alt="reason" src="https://user-images.githubusercontent.com/34123848/154794597-c6964e50-db40-4218-a908-11ac5b38c0c1.png">

**Comment by fvictorio** [comment]
Hi, we just released a beta version of a new plugin, `@nomicfoundation/hardhat-chai-matchers`. It should work as a drop-in replacement of hardhat-waffle, and (among other things) it fixes this issue. Check [this doc](https://nomiclabs.notion.site/Public-Hardhat-Chai-Matchers-11feb9185dd54591999f4e813f90c10c) if you are interested in giving it a try.

**Comment by lukehutch** [comment]
> Hi, we just released a beta version of a new plugin, `@nomicfoundation/hardhat-chai-matchers`. It should work as a drop-in replacement of hardhat-waffle, and (among other things) it fixes this issue. Check [this doc](https://nomiclabs.notion.site/Public-Hardhat-Chai-Matchers-11feb9185dd54591999f4e813f90c10c) if you are interested in giving it a try.

I tried this out, but got the following warning, even though I removed `ethereum-waffle` as a dependency:

```
You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers.
```

and the following error

```
TypeError: Cannot destructure property 'deployContract' of 'waffle' as it is undefined
```

Can you please backport the fix for this substring match back to `hardhat-waffle`?

**Comment by fvictorio** [comment]
> got the following warning, even though I removed `ethereum-waffle` as a dependency

That shouldn't happen. Is your repo public?

> ```
> TypeError: Cannot destructure property 'deployContract' of 'waffle' as it is undefined
> ```

If you uninstalled `ethereum-waffle` and `@nomiclabs/hardhat-waffle` (which is what we suggest, so that's fine), then you'll get that error because waffle won't be there anymore. We don't have a `deployContract` function in our chai matchers because that's out of scope for that package. You can probably replace those with `const Contract = ethers.getContractFactory("Contract")` and `Contract.deploy()`.

> Can you please backport the fix for this substring match back to `hardhat-waffle`?

Unfortunately, that's not an easy thing to do, so I don't think we'll have the bandwidth to do it.

**Comment by lukehutch** [comment]
> > got the following warning, even though I removed `ethereum-waffle` as a dependency
> 
> That shouldn't happen. Is your repo public?

My repo is not public, sorry. It sounds like `ethereum-waffle` has to be uninstalled from npm modules, not just removed as a dependency? I just removed it as a dependency.

> If you uninstalled `ethereum-waffle` and `@nomiclabs/hardhat-waffle` (which is what we suggest, so that's fine), then you'll get that error because waffle won't be there anymore. We don't have a `deployContract` function in our chai matchers because that's out of scope for that package. You can probably replace those with `const Contract = ethers.getContractFactory("Contract")` and `Contract.deploy()`.

OK, I'll work on porting to the newer framework. Thanks for the tips.

**Comment by fvictorio** [comment]
> It sounds like `ethereum-waffle` has to be uninstalled from npm modules, not just removed as a dependency?

Correct, it should be uninstalled.

**Comment by lukehutch** [comment]
@fvictorio I had to install `ethereum-waffle` in both my project and for my user account to get this to work. Your porting tips worked. For the record (in case anyone else has the same porting issue), I was able to replace waffle's `deployContract` with:

```
async function deployContract(wallet, contractJSON, constructorArgs) {
    const instance = await ethers.ContractFactory.fromSolidity(contractJSON, wallet).deploy(...constructorArgs);
    await instance.deployed();
    return instance;
}
```

**Comment by fvictorio** [comment]
> I had to install `ethereum-waffle` in both my project and for my user account to get this to work.

I'm not sure I understood this, can you elaborate?

Also, if you have `ethereum-waffle` installed again, that means you are getting the warning all the time, which must be annoying. We might consider removing it (or adding some way to hide it via config) if it turns out that people can't just uninstall `ethereum-waffle` completely.

**Comment by lukehutch** [comment]
I tried uninstalling with `npm uninstall ethereum-waffle` inside my project, that didn't work (I still got the warning). So I tried `npm uninstall ethereum-waffle -D` and `npm uninstall ethereum-waffle -g`, that didn't work. I discovered I had another copy of the library in `~/node_modules`, and I couldn't figure out how to uninstall that, so I just removed all of `~/node_modules`. That still didn't fix the problem. Then I noticed that `npm uninstall` had left an empty directory at `MyProject/node_modules/@ethereum-waffle`, so I manually removed that. I was still seeing the warning. I did an `egrep -r` looking for it anywhere else, and I found that `hardhat-gas-reporter` and `solidity-coverage` both transitively depended upon `ethereum-waffle`. I tried removing these two dependencies from my project, and it still didn't fix it. I messed around some more, and I couldn't figure out any other way that `require.resolve` was finding `ethereum-waffle` -- so I modified the `require.resolve` source code to reveal where the module was found, and poof, magically the problem was resolved (it was a Heisenbug). Apparently there was some caching going on somewhere, and modifying that file invalidated the cache. It was a major headache to fix this though.

**Comment by fvictorio** [comment]
Ugh, yes, I think we should just drop that warning. Thanks a lot @lukehutch.

**Comment by fvictorio** [comment]
This works correctly in our new [hardhat-chai-matchers](https://hardhat.org/hardhat-chai-matchers/docs/overview). We don't have plans to backport this fix to hardhat-waffle, given that it's not a minor effort, but our chai matchers are a drop-in replacement so [migrating should be easy](https://hardhat.org/hardhat-chai-matchers/docs/migrate-from-waffle).
