### ISSUE TITLE
"LoggingEnabled : false",  in an 'out of process' hardhat node doesn't work.

### ISSUE THREAD

**Issue by iangregsondev** [NomicFoundation/hardhat#2352]
Hi,

I am running hardhat node as 'out of process', so I am physically running

```
npx hardhat node
```

I have the following in my hardhat config

```
networks: {
    hardhat: {
      loggingEnabled: false,
```

The output of the methods being called are still there even though the logging has been disabled. You can see them when anything is talking to the node.

This wasn't what I was expecting..

So, if I then call the following, it does disable the logging

```
 await hre.network.provider.send("hardhat_setLoggingEnabled", [
    false,
  ]);
```

So that worked, after successfully calling the "hardhat_setLoggingEnabled", no more logs can be seen.

Is this correct ?

I assumed that "logginEnabled" set to false should start the node with no logging but it does not.

Can you confirm if this is correct, maybe I am misunderstanding the "logginEnabled" setting?

Thanks.

**Comment by morgansliman** [comment]
Hi @iangregsondev , thanks for opening the issue!

This does appear to be a bug, and seems to be a quick fix so I've opened a PR to allow this to be configurable as you've described. This should be fixed in the next release after the PR gets merged, so feel free to keep an eye on that for updates! We'll also close this issue when we make that release as well.

Thanks!

**Comment by iangregsondev** [comment]
Thanks @morgansliman, much appreciated for looking at it.
