### ISSUE TITLE
Nested arrays inside structs are not included in generated ABI

### ISSUE THREAD

**Issue by kargakis** [NomicFoundation/hardhat#2433]
Using the latest `2.8.4` hardhat version, I have a minimal reproducer of the issue below. After compiling, I don't see the integer array `ids` as part of the generated ABI in `artifacts/contracts/Example.sol/Example.json`, neither as part of the mapping `mappedData` (which is what I wanted to use) nor in the top-level struct field `data`.
```js
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

contract Example {
    struct Data {
        uint256[] ids;
        uint256 createdAt;
        address user;
    }
    mapping (uint256 => Data) public mappedData;
    Data public data;
}
```
FWIW I have also tried with a different type of nested array (eg. `address[]`) and it also has the same issue so it doesn't look type-specific.

**Comment by murderteeth** [comment]
@alcuadrado I might find time to help\PR something. Could you point me in the right direction for this? Or maybe its a problem in ethers?

**Comment by alcuadrado** [comment]
Hey, sorry for the late reply @kargakis!

This is actually a solidity/evm limitation. It doesn't return the entire array. It's unfortunate that it's just ignored instead of printing a warning or something.

We save the abi as solc returns it, so this can't be our issue, and I just validated your minimal reproduction.

I'm closing this issue, but feel free to open a new one in solidity's repo and tag me.
