### ISSUE TITLE
hardhat fork - add rpc api to trigger reorg simulations

### ISSUE THREAD

**Issue by krasi-georgiev** [NomicFoundation/hardhat#2443]
Often when  constructing local state from logs need to write tests to verify the state  during reorgs. 
Is this something the team would be willing to look into adding to the fork rpc endpoints?

**Comment by fvictorio** [comment]
Yes! I think this would be a handy feature.

Can you tell us how you imagine this working? I guess that we could accomplish this with snapshots if they worked in a different way than they do now.

1. The chain is at block 1000. You take a snapshot `A`.
2. You mine 2 blocks and take another snapshot `B`.
3. You revert to the snapshot `A`. The latest block is again 1000.
4. You mine 4 blocks (and the first two are different than the ones you mined in step 2).
5. You take a snapshot `C`.

Now you can go to snapshot `B` and then move to `C` to simulate a reorg.

This can't be done with our current implementation of snapshots because when you revert to `A` in step 3, the snapshot `B` is discarded.

Also, this is very convoluted. But it could be a building block on top of which something more ergonomic could be built (for example: a method that takes a block number and a group of transactions, and simulates a reorg by going back to that block number and mining all those transactions).

**Comment by krasi-georgiev** [comment]
not sure if it will work with snapshots. In golang when I make a subscription to events when there is a re-org the same event is sent with a flag - removed. I don't think the same will happen when using snapshots.

for example, chain is at 1000, mine a TX which emits an event A - trigger a reorg the same event A is sent with a flag A-removed, usually right after that if the same TX is included in the new block the same event might be repeated without the remove flag to mark it that regardless of the re-org it is still included in the new block. Ideally to make the tests extensive both cases should be doable - reorg where the TX is included in the new block and a re-org where the TX same TX is not included in the new block.

**Comment by krasi-georgiev** [comment]
had a quick look and it seems that the go client uses the block number and hashes to detect re-orgs so maybe snapshots will work.

https://github.com/ethereum/go-ethereum/blob/acd7b369994887b342be03f8cf11cf617d8ac278/core/blockchain.go#L1937-L1989

Could you maybe give an example of how would I need to call the snapshot commands to see if the client will detect is a re-org?

**Comment by fvictorio** [comment]
> Could you maybe give an example of how would I need to call the snapshot commands to see if the client will detect is a re-org?

I don't think it's possible to do it with our current implementation of snapshots :slightly_frowning_face:

**Comment by fvictorio** [comment]
Hmm, I think I could publish a hacky implementation that lets you do this under a `dev` tag, at least to validate the idea.

**Comment by krasi-georgiev** [comment]
sure, lets give it a try

**Comment by krasi-georgiev** [comment]
stil relevant

**Comment by pokrovskyy** [comment]
Now in post-Merge world - is this still even a thing? (I mean reorgs)

**Comment by nshCore** [comment]
> Now in post-Merge world - is this still even a thing? (I mean reorgs)

yes this is still very much needed, eth switching to POS doesn't change the finality of a block, and when using other networks such as Polygon that have frequent deep reorgs, it still is a highly desired feature.

looking quick over the ethereumjs vm snapshot, revert and remine with the option of including or removing a transaction and being able to assert the correct events and state changes are made, or application logic handles reorg correctly would be a big win for most developers who have had to debug systems that do not have any reorg handling logic
