### ISSUE TITLE
Cronoscan not listed in Verify types

### ISSUE THREAD

**Issue by kryptobaseddev** [NomicFoundation/hardhat#2584]
Need to be able to run the verify for Cronoscan Mainnet and Testnet. I have found that Truffle has a package for this but most everything  in my builds are configured with Hardhat config. 

Can we get a status on when Cronos chain will be added to the repo?

**Comment by fvictorio** [comment]
Hi @kryptobaseddev, we are going to stop adding networks to the core of `hardhat-etherscan`, or at least slow down on that, because it takes a lot of time to manually test new chains. But there is now a way to do it without waiting for us to add support in the plugin itself. [This comment](https://github.com/NomicFoundation/hardhat/pull/2441#issuecomment-1116382707) explains how to do it. It's in RC status, but it should work fine.
