### ISSUE TITLE
Please change Setting up environment guide from node 12 to 15 : node 12 doesn't work on on M1 macOS 

### ISSUE THREAD

**Issue by janetcheung-byte** [NomicFoundation/hardhat#2624]
I use a M1 macOS computer. From https://hardhat.org/tutorial/setting-up-the-environment.html, I follow the instruction of Mac OS to set up the environment with these commands:
```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash
nvm install 12
nvm use 12
nvm alias default 12
npm install npm --global # Upgrade npm to the latest version
```

When I type "npx hardhat" command, I end up getting error message telling me like this "wasm code commit Allocation failed - process out of memory]".
The best example of the error is at this stacker flow [link](https://stackoverflow.com/questions/65856300/wasm-code-commit-allocation-failed-process-out-of-memory).

After changing to from node 12 version to node 15, "npx hardhat" command work for me. Please the instruction to this:

```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash
nvm install 15
nvm use 15
nvm alias default 15
npm install npm --global 
```

Thank you,

Janet

**Comment by feuGeneA** [comment]
Hi, and thank you for using Hardhat. I'm sorry to hear of your trouble, but it wouldn't make sense for us to disable support for Node 12 on all platforms simply because it doesn't work on one platform. However, if its any consolation to you, our policy is to discontinue support for Node versions two months after they reach End-of-Life status, and for Node 12 that status was reached on April 30, 2022.
