### ISSUE TITLE
Unable to call simplest method of freshly deployed contract.

### ISSUE THREAD

**Issue by hickscorp** [NomicFoundation/hardhat#2658]
Good afternoon,

I'm completely new to Hardhat (but am quite experienced with other frameworks).

Consider the following contract:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

contract Registry {
  function foo() public pure returns (uint256) {
    return 42;
  }
}
```

It's being deployed like so:
```typescript
import { ethers, upgrades } from "hardhat";

async function main() {
  const Registry = await ethers.getContractFactory("Registry");
  const registry = await Registry.deploy();
  // const registry = await upgrades.deployProxy(Registry);
  await registry.deployed();
  console.log(`Registry deployed to ${registry.address}.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```

Then, using `hardhat node`:
```javascript
const Registry = await ethers.getContractFactory("Registry");
const registry = await Registry.attach(REGISTRY_DEPLOYED_ADDRESS);
await registry.foo();
```

This errors:
```
Uncaught:
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="foo()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.1)
    at step (whatever/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Contract.<anonymous> (whatever/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at Interface.decodeFunctionResult (whatever/node_modules/@ethersproject/abi/src.ts/interface.ts:429:23)
    at Logger.throwError (whatever/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.makeError (whatever/node_modules/@ethersproject/logger/src.ts/index.ts:261:28) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'foo()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x5fbdb2315678afecb367f032d93f642f64180aa3',
  args: [],
  transaction: {
    data: '0xc2985578',
    to: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    gasLimit: BigNumber { value: "29021272" }
  }
}
```

What am I doing wrong here?

**Comment by matabeitt** [comment]
Are you using the following?

```sh
# npx hardhat run --network <network> script.js
npx hardhat run --network hardhat script.js
```

Where <network> is configured in your `hardhat.config.js` like so:

```ts
const config: HardhatUserConfig = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: { ... }
  }
};
```

**Comment by fvictorio** [comment]
@hickscorp If you are using the Hardhat node, then the approach you use is usually something like this:

1. In one terminal, start the node with `npx hardhat node`
2. In another terminal, run your deploy script with `npx hardhat run --network localhost deploy.js`
3. After that, you can run the code that does the `.attach`, but you have to use `--network localhost` again.

If you don't use `--network localhost`, then the default network, `hardhat`, will be used. This is an ephemeral, in-process network that is created with the command you are running and it's destroyed when it finishes. So if you deploy in that network and then run another script that does the `.attach` thing, this second script will try to make a call to an empty address (because nothing was deployed there).

You can [read this](https://hackmd.io/@fvictorio/hardhat-networks-and-providers) for a more in-depth explanation.

Hope that helps!

**Comment by cesarvarela** [comment]
Omg, I've spent a few hours dealing with this. 

Maybe a callout somewhere around the docs may save future developers some time? 

I think the intuition here is that it will use the localhost network by default (probably because of expecting something similar to web2 development).
