### ISSUE TITLE
is it support to https hardhat network for development on a intranet

### ISSUE THREAD

**Issue by choigawoon** [NomicFoundation/hardhat#2682]
hello, i'm trying to make a dapp on the intranet for POC.
and metamask or other such as wallet app ask me to use https rpc address when using their APIs.
for security reason, i cannot use tunnel like ngrok and so on.
i want to run my npx hardhat network with ssl if it possible.

**Comment by fvictorio** [comment]
Hi @choigawoon. I think the best way for you to accomplish this is to use some proxy that adds support for https. For example, searching for "https localhost proxy" suggests [this package](https://github.com/cameronhunter/local-ssl-proxy). I haven't tried it though, but that's the kind of thing that you should probably use.

I'm closing this because it's unlikely that we'll be able to work on this, at least not in the short/middle term.
