### ISSUE TITLE
Rinkeby deployment not working

### ISSUE THREAD

**Issue by 0xTimepunk** [NomicFoundation/hardhat#2690]
Suddenly rinkeby deployments do not work (are stuck) in hardhat  hardhat run --network rinkeby scripts/deploy.ts

Rinkeby network doesn't seem down and hardhat does not provide any information about what's happening.

I tried setting gas and gasPrice in hardhat config without any help

```
    rinkeby: {
      url: 'https://eth-rinkeby.alchemyapi.io/v2/' + process.env.ALCHEMY_TOKEN,
      accounts: {
        mnemonic: process.env.MNEMONIC as string,
      },
      gas: 2100000,
      gasPrice: 8000000000,
    },
```

The strangest thing is that this deployment was working yesterday.
I tried deploying to rinkeby on different repos that were previously working and they are stuck as well. Asked a colleague to do the deployment and tried in a different pc and it is also stuck.

**Comment by kowalski** [comment]
I think I've seen a similar problem and was able to debug this a bit further. 
I don't think that changing the endpoint to Infura made a difference. What made a difference are network conditions on Rinkeby and the fact that it took some time.

Let me explain.

I think the problem is here: 
https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/core/providers/gas-providers.ts#L278

When sending a type=2 transaction provider calculates fee parameters as:
```
maxFeePerGas = 81/64 * baseFeeFromLastBlock
maxPriorityFeePerGas = maxPriorityFeePerGasFromLastBlock
```

This formulas work fine for Mainnet but not for Rinkeby. Difference is that for Rinkeby it's normal to priorityFeePerGas be roughtly equal to baseFee. On Mainnet priority fee is much lower when compared to baseFee.

The kicker is that:

```
maxFeePerGas = maxBaseFeePerGas + maxPriorityFeePerGas
```
 
Since `_suggestEip1559FeePriceValues` sets:

```
maxFeePerGas = 1.41 * baseFeePerGas
```

It means that it will work only if priorityFee is lower than `0.41 * baseFeePerGas`. This is true for mainnet and usually is true for Rinkeby. But sometimes it's not true for Rinkeby and when it's not the only was to have this working is to pass fee parameters explicitely to `deploy` function.

My suggestion for a fix:

```
        maxFeePerGas: rpcQuantityToBN(response.baseFeePerGas[1])
          .mul(
            new BN(9).pow(
              new BN(
                AutomaticGasPriceProvider.EIP1559_BASE_FEE_MAX_FULL_BLOCKS_PREFERENCE -
                  1
              )
            )
          )
          .div(
            new BN(8).pow(
              new BN(
                AutomaticGasPriceProvider.EIP1559_BASE_FEE_MAX_FULL_BLOCKS_PREFERENCE -
                  1
              )
            )
-         ),
+        ).add(rpcQuantityToBN(response.reward[0][0])),
        maxPriorityFeePerGas: rpcQuantityToBN(response.reward[0][0]),
```

Rational: this changes the calculation as:

```
maxFeePerGas = 1.41 * baseFeePerGas + previousMaxPriorotyFeePerGas
```
therefore correctly encapsulates the maximum required fee (assuming 2 blocks where produced with 200% gas limit usage)
