### ISSUE TITLE
Hardhat not displaying correct error message

### ISSUE THREAD

**Issue by ChinmayGopal931** [NomicFoundation/hardhat#2720]
When I run `yarn test` I get a `     Error: Transaction reverted without a reason string` without any further information.

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  If there is a problem with Hardhat, we will need much more information in order to fix it. In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example If you're sure there's a problem with Hardhat, and you can document it, feel free to re-open this issue.

For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.
