### ISSUE TITLE
Better error message when URL is an empty string

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#2730]
An empty string in the forking URL or in a network URL produces this error message:

```
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL:
```

We should handle this as a special case and print a better error message. Also, this is not caught during config validation; instead, it happens the first time a request is sent.

[This comment](https://github.com/NomicFoundation/hardhat/issues/2244#issuecomment-1121306153) also seems to suggest that an "only absolute URLs are supported" message can be shown when an empty string is used; maybe that depends on the OS or it happens in other scenarios.

**Comment by ZainGulbaz** [comment]
Hi @fvictorio , Can you please assign this issue to me? Thanks.

**Comment by ZainGulbaz** [comment]
Hi @fvictorio , I have made a pull request for it. You can have a look. Thanks.

**Comment by ZainGulbaz** [comment]
#3825

**Comment by ZainGulbaz** [comment]
#3825 better message when url is an empty string.

**Comment by kshyun28** [comment]
Hello @fvictorio, I'm looking at the list of good first issues and am interested in taking a stab at this issue if its okay.

P.S. your evm-puzzles were really helpful in making me understand evm at a practical level :)

**Comment by kshyun28** [comment]
I have a question, am trying to run tests in the `hardhat-core` package. It's requiring me both `ALCHEMY_URL` and `INFURA_URL`.
![image](https://github.com/NomicFoundation/hardhat/assets/56709653/cd358968-503f-41e0-821c-34f3e29676fc)

I've added a file `packages/hardhat-core/.env` and populated with the following, but still shows the same error. 
```
INFURA_URL=https://sepolia.infura.io/v3/[REDACTED]
ALCHEMY_URL=https://eth-sepolia.g.alchemy.com/v2/[REDACTED]
```

- Where should I be setting the environment variables? 
- And is using Sepolia HTTP url correct, or should I use another network (Mainnet, Goerli, etc.)?

**Comment by fvictorio** [comment]
Hey @kshyun28, sorry for not responding sooner and thanks for the PR!

> Have used mainnet rpc urls after seeing tests fail on Sepolia rpc. Might be obvious, but wasn't clear to me as a first time potential contributor.

That's a great point. Do you want to send a separate PR improving that warning? Ideally we would change the environment variables names too, but that will be a huge change and maybe it's not worth it

> your evm-puzzles were really helpful in making me understand evm at a practical level

Super glad to read that :smile:

**Comment by kshyun28** [comment]
> That's a great point. Do you want to send a separate PR improving that warning? Ideally we would change the environment variables names too, but that will be a huge change and maybe it's not worth it
> 
I'm okay with sending an additional PR to improve the warning message. Currently I'm thinking `TEST RUN INCOMPLETE: You need to define the env variable INFURA_URL to an Ethereum mainnet HTTP provider`

I'd also suggest to add a section in [CONTRIBUTING.md](https://github.com/NomicFoundation/hardhat/blob/main/CONTRIBUTING.md) on configuring environment variables for tests as needed. A note/hint could work, since I only knew that environment variables are needed after attempting to run the test. 

Might have to review if steps to configure env variables are the same in windows, but `export VARIABLE=value` should work on mac/linux.

## Testing

All tests are written using [mocha](https://mochajs.org) and [chai](https://www.chaijs.com).

### Environment variables

Some tests require having `INFURA_URL` and `ALCHEMY_URL` configured. You can set them in your terminal using `export ALCHEMY_URL=value INFURA_URL=value`.

### Per-package

You can run a package's tests by executing `yarn test` inside its folder.

### Entire project

You can run all the tests at once by running `yarn test` from the root folder.
