### ISSUE TITLE
hardhat_mine won't work with valid hex string

### ISSUE THREAD

**Issue by gbarros** [NomicFoundation/hardhat#2783]
The code block bellow won't work on version `2.9.7`.  (I didn't test other versions, I upgraded straight to lastest).

I was updating my test utility functions to use `hardhat_mine` and it's a common practice of "toHex" functions to produce strings with pairs for hex numbers. It means that the 256 blocks example given would actually produce the zero before the 1. 
```
// mine 256 blocks
await hre.network.provider.send("hardhat_mine", ["0x0100"])
```

You can check the produced hex strings on common functions such as:
```
ethers.utils.hexlify(256)
BigNumber.from(256).toHexString()
```

The error produced on tests is the following: 
```
 InvalidArgumentsError: Errors encountered in param 0: Invalid value "0x0100" supplied to : QUANTITY | undefined
 ```

**Comment by fvictorio** [comment]
Hi @gbarros, thanks for reporting this.

This is a common problem that comes from the fact that the `QUANTITY` type, as defined by the spec, doesn't allow leading zeroes. Since `hardhat_mine` is a custom method, we could be more permissive here and use a different type (one that allows these leading zeros), but so far we've opted for consistency.

But we are aware this is an annoying problem. One way we are trying to address it is with a set of helpers that let you interact with the network in a more ergonomic way. We released a beta version of this, and we'll release a stable version soon, but they can be used right now. In fact, we really appreciate people trying them out now, to get early feedback. You can read more about them [here](https://nomiclabs.notion.site/Public-Hardhat-Network-Helpers-216cf3c665124895bf1f6e2f9343f86f), but the tl'dr is:

1. Install the package with `npm i @nomicfoundation/hardhat-network-helpers@beta`
2. Use it in your code like this:

    ```js
    const helpers = require("@nomicfoundation/hardhat-network-helpers")
    
    await helpers.mine(1000)
    ```

Using this method has several advantages:

- Many kind of values are accepted, like plain numbers, native bigints, ethers's bignumbers, hex-strings (even with leading zeros).
- The resulting code is shorter and nicer
- You get type-checks, better error messages, auto-complete for discoverability, and so on.

I'm going to leave this issue open for now, but to be honest it's probably going to be a "won't fix". Please let me know if you disagree with this decision.

**Comment by gbarros** [comment]
I like that idea of a helpers package a lot and I'll be using it for sure =)

However, I'd take into consideration other users/scenarios that would try to connect straight through the RPC and suffer with this issue.

I'm good though, thanks a lot!

**Comment by fvictorio** [comment]
> and I'll be using it for sure =)

Thanks a lot! Any feedback about them is very welcome.

> However, I'd take into consideration other users/scenarios that would try to connect straight through the RPC and suffer with this issue.

My take is that users just trying to interact with the network should use these helpers, and people using the RPC interface directly are most likely doing something advanced, and therefore having to follow the spec to the letter shouldn't be a concern. But this is a wild guess, I'm open to being proven wrong about this in the future :sweat_smile: 

> I'm good though, thanks a lot!

In that case, I'll just close this, thanks!
