### ISSUE TITLE
`/hardhat-network/index.md` giving 404 in docs

### ISSUE THREAD

**Issue by skaunov** [NomicFoundation/hardhat#2815]
Throughout the docs there are few links to the page `/hardhat-network/index.md` which returns error 404 to user. I believe it would improve overall experience if these links would be repaired.

**Comment by iKausik** [comment]
@skaunov Can you redirect me to those pages?

**Comment by skaunov** [comment]
@iKausik  Sorry, can't make anything like a list right now, but just as an example: <https://hardhat.org/hardhat-network/reference#initial-state> links to <https://hardhat.org/config/index.md#hardhat-network> in the end of the section. Obviously "/index.md" is added incorrectly during the pipeline.

**Comment by skaunov** [comment]
Another examples are first internal links at <https://hardhat.org/guides/waffle-testing>. It should already demonstrate the nature of the problem.

**Comment by feuGeneA** [comment]
We recently overhauled the documentation, and to my knowledge fixed a handful of these. From what I can tell, there's only one left:

`src/content/hardhat-runner/docs/other-guides/ganache-tests.md:Rather than using Ganache, we recommend using the built-in [Hardhat Network](../hardhat-network/index.md) network to test your smart contracts, as it generates [combined JavaScript and Solidity stack traces](../hardhat-network/index.md#solidity-stack-traces), making debugging easier.`

And, it seems to me that that page is only accessible by URL at this point (not by navigating page links from the documentation landing page).

**Comment by fvictorio** [comment]
I believe these are fixed, but please let us know if that's not the case.
