### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - HH Network Reset

### ISSUE THREAD

**Issue by julianmrodri** [NomicFoundation/hardhat#2869]
We are facing a `FATAL ERROR: Reached heap limit Allocation failed` crash in all our Tests that perform a `hardhat_reset` action. This does not happen locally and only occurs when running in Github Actions (CI). The error thrown in CI (Github action) is the following:

```
<--- Last few GCs --->
[2095:0x62c1840]    23100 ms: Scavenge (reduce) 2046.7 (2082.8) -> 2046.7 (2083.8) MB, 8.1 / 0.0 ms  (average mu = 0.298, current mu = 0.159) allocation failure 
[2095:0x62c1840]    23947 ms: Mark-sweep (reduce) 2047.6 (2083.8) -> 2047.5 (2084.5) MB, 786.2 / 0.0 ms  (+ 309.4 ms in 98 steps since start of marking, biggest step 14.6 ms, walltime since start of marking 1154 ms) (average mu = 0.221, current mu = 0.085
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
....
```

Here I provide a simplified repo that can be used to reproduce the issue: https://github.com/julianmrodri/hhreset-ci-issue 
Instructions have been provided in the repo to reproduce and understand what could be causing this failure.

**HINT:** An interesting thing we noticed is that this error can be fixed by simply removing one of the contracts in our repo, although this contract is NOT USED in any test or deployment script. Which indicates there might be some types of contracts that break the HH Network during CI execution, even if they are not used in the actual test. A PR has been created in the provided repo so you can take a look how this fixes the issue.

Any additional information you need please let me know.

**Comment by feuGeneA** [comment]
Thank you for your patience. This is high on our team's list of items to triage.

**Comment by fvictorio** [comment]
Hey @julianmrodri, thanks for the great reproduction repo and sorry for not responding sooner.

I could indeed reproduce the problem, but I also noticed that upgrading both Hardhat and solidity-coverage to their latest versions seems to fix it. My guess is that this was fixed by an improvement we implemented in our compilation pipeline, which made many OOM errors like this go away.

I'm going to tentatively close this now, but please let me know if you are still running into this after upgrading.
