### ISSUE TITLE
debug_traceTransaction returns different gas usage than the original TX

### ISSUE THREAD

**Issue by krasi-georgiev** [NomicFoundation/hardhat#2917]
"hardhat": "^2.10.0",
"node": "^18.5.0"

I ran simulations on a few TX on mainnet and avalanche and each one returns a different TX usage than the one reported on etherscan.
Running the same simulations on Tenderly returns the exact gas usage as the one reported on etherscan.

**Comment by krasi-georgiev** [comment]
```
npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/....
curl -s --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x82e8cbbf48b57dd16b111da5a826d8d1874541283d5a4e2028d9153a9ea080ea"],"id":"1"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```
result for gat is `185,780` actual gas is `281,958`

https://etherscan.io/tx/0x82e8cbbf48b57dd16b111da5a826d8d1874541283d5a4e2028d9153a9ea080ea

**Comment by krasi-georgiev** [comment]
Here is how to replicate

```
npx hardhat node --fork https://api.avax.network/ext/bc/C/rpc --fork-block-number 17154874

curl -s --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x9f8b8623b643e0d930163528ccd56bc0fe087f1ee27510d1ca0a0b6a4217aac6"],"id":"1"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```
actual gas usage is `136,573` hardhat reports gas usage `109,259`
https://snowtrace.io/tx/0x9f8b8623b643e0d930163528ccd56bc0fe087f1ee27510d1ca0a0b6a4217aac6

**Comment by alcuadrado** [comment]
Hey @krasi-georgiev, 

Unfortunately, we can't guarantee that Hardhat Network has the same gas costs as every evm chain. If the C-Chain has the same gas costs as mainnet, and you set the Hardhat Network `hardfork` config to match the C-Chain's they'll match, otherwise they won't. IMHO changing the gas costs in an EVM network is a mistake, as there are tons of small incompatibilities that you introduce by doing so.
