### ISSUE TITLE
Hardhat Still Saying "Nothing to compile"

### ISSUE THREAD

**Issue by RomeDomeYome** [NomicFoundation/hardhat#3024]
I followed an earlier thread where several people were having issues when following the tutorial for hardhat on their website. Even after I did what the user recommended in this thread comment--:
"Hi everyone, we just released [`hardhat@2.9.6`](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.6), which fixes this issue. Please try it out and let us know if you are still getting the same problem. Thanks!"

_Originally posted by @fvictorio in https://github.com/NomicFoundation/hardhat/issues/2712#issuecomment-1132181614_

--it still will not compile Token.sol
It just says "nothing to compile" when I run npx hardhat compile
I'm not really sure what I am doing wrong, I feel like I've tried everything at this point. Does anyone know how to fix this?
Im running this In a WSL: Ubuntu window on Windows.
I have hardhat version 2.10.2-dev.0

**Comment by feuGeneA** [comment]
Thank you for using Hardhat.

In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example

Can you provide us with a minimal reproducible example? If so, feel free to re-open this Issue.

Also, please be aware that "Nothing to compile" is an expected message in the case where your contract has already been compiled (the compilation output is already present in your `artifacts` folder). The message may be interpreted as "Contract already compiled."

Having said all that, if you still need help, please also be aware that GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

**Comment by feuGeneA** [comment]
Please know that this message, "Nothing to compile" is expected and normal in the case where your contract has already been compiled (its compiler output is already present in your `artifacts` folder).

In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example

Can you provide us with a minimal reproducible example? If so, please feel free to re-open this issue.

Please also be aware that GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.
