### ISSUE TITLE
bytecode recorded on deployment suddenly not matching bytecode of artifacts 

### ISSUE THREAD

**Issue by matthewlilley** [NomicFoundation/hardhat#3263]
We have various commits, such as this one throughout the history of the repository. This is the first where deployments were extracted so we have a copy of the bytecode upon deployment.

https://github.com/sushiswap/trident/commit/f730debcec2d50cb92e4b0c0200b1d81f81bb9b4

If you were to clone this repostiory and checkout this commit, run hardhat build & compare bytecode from artifacts e.g. ConstantProductPoolFactory.json against the polygon deployment for the same file they are no longer matching.

This protocol has been deployed on a number of networks over 6 months, but now it's impossible to find any point in time where artifacts generated at those deployment commits will have the same bytecode found in the deployment file. 

This is really odd... It feels like this is related to a loose dependecy of hardhat which has forced an update behind the scenes or something. It's difficult to debug but definitely an issue since it can be easily shown that determism has been lost since we've recorded our bytecode on deployment, and can no long match this up with generated artifacts at any point in the history of our repositoy.

**Comment by fvictorio** [comment]
> against the polygon deployment for the same file they are no longer matching.

Can you share a link to that contract in the Polygon explorer?

**Comment by fvictorio** [comment]
Nevermind, I just saw that that is saved in the deployments. I'll look into this as soon as I have some time.

**Comment by sarangparikh22** [comment]
There has been more development on this, so, we re-deployed and the bytecode and deployedBytecode on the deployments folder match as that of older deployments, however they are different from the artifact.

**Comment by matthewlilley** [comment]
@fvictorio Yeah, this appears to be a regression. If we deploy we're getting the correct bytecode, but generated artifacts never match the deployed contract. I'll touch up our artifacts manually for now until you have a chance to dig into this more deeply.

**Comment by fvictorio** [comment]
Ok, sharing my findings here, although I don't know how helpful they will be.

I compared the (deployment, not deployed) bytecode of the `ConstantProductPoolFactory` contract as obtained from compiling the project in that commit, and the deployment bytecode indicated in the `deployments` file.

The first 41426 characters of the bytecode are the same. The final part is different, which usually means that the metadata is different. But in this case there is an extra fun added because there are two metadatas involved, and the two are different.

These are the last characters of each bytecode, split into lines to make it easier to see:

```
a2646970667358221220
2f9fb6aa3dd81d974058981cd60b5b9a73205462b7f1289fb1c3d2aa89f2f817
64736f6c634300080a0033
a2646970667358221220
d1454cd6da4a6737aa0a6a44d45bdcc7e744e878a914301886efa4efc1195931
64736f6c634300080a0033
```

```
a2646970667358221220
23b1b16732d5efbbde4fe9c09ad57bc5e282ee9d8115186daf2a0c35f79fae82
64736f6c634300080a0033
a2646970667358221220
2574e272fe091577903e8619f249f8e3e1f3373c680480c579a6639f1784d57a
64736f6c634300080a0033
```

You can see that the 2nd and 5th lines are different, but the other ones are the same. This is because only the hash part of the metadata are different. The rest, like for example the solc version (`00080a`, which is `0.8.10`) are the same.

The first metadata corresponds to the bytecode of the `ConstantProductPool` contract, which is inside the factory bytecode. The second metadata is the one that corresponds to the factory bytecode itself.

So, the weird thing here is that the metadata of the `ConstantProductPool` factory is different (even when the bytecode is the same), and this of course causes the metada
of the factory to also change.

The important  thing to notice here is that **the executable part of the bytecode is the same in both cases**. So why did this change? I have no idea. Maybe someone changed a comment in the `ConstantProductPool` contract, and this produced a change in its metadata, in the metadata of the inlined bytecode inside the factory, and in the metadata of the factory. Presumably this also changed the metadata of the contract bytecode itself, but since that contract is not part of the `deployments` file (only the factory is), we have no way of knowing.

Btw, I only skimmed the deployed bytecodes, but I'm pretty sure the same analysis applies.

**Comment by fvictorio** [comment]
Changing a comment in the `ConstantProductPool.sol` file (not factory) indeed produces a change in the exact same two places.

Changing a comment in the `ConstantProductPoolFactory.sol` file only produces a change in the second point (the metadata).

All of this is expected, just sharing because it further confirms my theory.

**Comment by fvictorio** [comment]
I think I'm going to close this one because there isn't much we can do. Happy to re-open if you think otherwise.
