### ISSUE TITLE
network specific code

### ISSUE THREAD

**Issue by shirotech** [NomicFoundation/hardhat#3290]
Hi there, I've been searching but have not found if this feature is possible.

Is there a decorator which allows if the specific block of code is only for a specific network?

E.g. we have some init code for unit test, but would like it removed when compiling for mainnet. What is the way to go about this not having to mess around with adding and removing code? Thank you.

**Comment by fvictorio** [comment]
You mean adding and removing Solidity code for different networks?

**Comment by shirotech** [comment]
> You mean adding and removing Solidity code for different networks?

In a way, yes.

**Comment by fvictorio** [comment]
No, there's no built-in way to do that, and it's unlikely we would add something like that to Hardhat core.

I'd suggest you take a look at https://github.com/wighawag/hardhat-preprocessor, since you could build something like this on top of that (by checking the value of `hre.network.name` in the preprocessing function or something like that). It's not easy, but it should be doable.
