### ISSUE TITLE
Error while loading custom solidity compiler

### ISSUE THREAD

**Issue by r0qs** [NomicFoundation/hardhat#3295]
### The Problem

When attempting to use a custom solidity compiler that was not released yet the hardhat-core tests fail with `HardhatError: HH11: An internal invariant was violated: Trying to get a compiler before it was downloaded` since the `_getCompilerBuild` function returns `undefined` because the compiler version does not exist in the `list.json`.

https://github.com/NomicFoundation/hardhat/blob/5c31db69a0981440c17dc7d24f8deeeaf5bc8f32/packages/hardhat-core/src/internal/solidity/compiler/downloader.ts#L225

### To reproduce the bug

You can reproduce the bug by setting `HARDHAT_TESTS_SOLC_VERSION` to a non-released version like in the script below.

```sh
#!/bin/bash

(
  wget -c https://binaries.soliditylang.org/bin/soljson-v0.8.16+commit.07a7930e.js -O soljson-v0.8.16.js
  export HARDHAT_TESTS_SOLC_PATH=$(pwd)/soljson-v0.8.16.js
  export HARDHAT_TESTS_SOLC_VERSION=0.8.18 # <---- some version that was not released yet
  mkdir -p tmp && cd tmp
  git clone --depth 1 https://github.com/nomiclabs/hardhat.git
  cd hardhat
  ./scripts/run-tests-with-custom-solc.sh
)
```

### Expected behavior

Setting a custom compiler with `HARDHAT_TESTS_SOLC_PATH` should be possible even though the version is not a solc release. Note that in the script above the version `v0.8.16` was used as an example, but it could be your own solidity local build: `export HARDHAT_TESTS_SOLC_PATH=<your_solidity_repo>/build/solc/solc`

**Comment by cameel** [comment]
A bit more context: looks like it's not simply about `HARDHAT_TESTS_SOLC_VERSION`. The whole mechanism for supplying a custom binary seems broken. In cases where the version is one of the released versions, Hardhat tries to use a downloaded binary instead of the one specified in `HARDHAT_TESTS_SOLC_PATH`. And with 0.8.16 it was passing for us only due to cache. After removing cached compiler binaries, tests fail.
