### ISSUE TITLE
Error HH303: Unrecognized task e2e/runner.ts

### ISSUE THREAD

**Issue by NicoAtScopely** [NomicFoundation/hardhat#3332]
Hi there,

I'm having an issue running a simple script from package.json. Here's my script:
`"e2e": "SHARDHAT_BIN=./node_modules/.bin/ts-node npx shardhat e2e/runner.ts"`

And here's my runner.ts file:
```
import mocha from 'mocha'

let mochaRunner = new mocha();
console.log('Test');
mochaRunner.addFile(__dirname + '/e2e.ts')
mochaRunner.run(function(failures) {
    process.exitCode = failures ? 1 : 0;  // exit with non-zero status if there were failures
}); 
```

For some reasons, When running `npm run e2e`, I get the following error message:
```
nicolas.ma@MacBook-Pro web3-contracts-evm-test-project % npm run e2e --show-stack-traces

> web3-contracts-evm-test-project@1.0.0 e2e
> SHARDHAT_BIN=./node_modules/.bin/ts-node npx hardhat e2e/runner.ts
Error HH303: Unrecognized task e2e/runner.ts
For more info go to https://hardhat.org/HH303 or run Hardhat with --show-stack-traces
```

Any idea where this issue comes from ? My file is well located under "e2e/runner.ts". It is not mispelled.

**Comment by alcuadrado** [comment]
What's shardhat? 0.o

**Comment by NicoAtScopely** [comment]
It's a wrapper we created but the issue does not come from there. I tried changing it into
`"e2e": "SHARDHAT_BIN=./node_modules/.bin/ts-node npx shardhat e2e/runner.ts"`
and the output is exactly the same :(

**Comment by fvictorio** [comment]
You are doing `npx hardhat e2e/runner.ts` instead of `npx hardhat run e2e/runner.ts`. You need to use the `run` task to run scripts.

This is not the first thing something like this happens. We should detect that the "task" name that we received happens to match a path to a file, and show a proper suggestion. I opened https://github.com/NomicFoundation/hardhat/issues/3334 for that.
