### ISSUE TITLE
Is Node 19 supported?

### ISSUE THREAD

**Issue by marcosmartinez7** [NomicFoundation/hardhat#3341]
Is node 19 supported on latest version of hardhat? 

Im getting the following warning when `nom install` into a new hardhat project.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hardhat@2.12.2',
npm WARN EBADENGINE   required: { node: '^14.0.0 || ^16.0.0 || ^18.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.0.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

Also, when using [slither-actions](https://github.com/marketplace/actions/slither-action) the pipeline fail when installing hardhat 2.12.2 for the same reason

<img width="983" alt="image" src="https://user-images.githubusercontent.com/14795944/201434092-31de7a2c-7feb-431f-8e74-91ed6bfa4dcf.png">

**Comment by fvictorio** [comment]
Hi @marcosmartinez7, we only (officially) support node's LTS versions, as you can read [here](https://hardhat.org/hardhat-runner/docs/reference/stability-guarantees#node.js-versions-support).

That being said, maybe having that in the engines section is too restrictive, since things are likely to work in non-LTS versions too (maybe).

@alcuadrado should we drop the `engines` from the `package.json`, and replace it with some warning similar to the solidity one?

**Comment by alcuadrado** [comment]
> @alcuadrado should we drop the `engines` from the `package.json`, and replace it with some warning similar to the solidity one?

Yes, I like this idea!

Even more so, I think we should have a very lean entry to the CLI that just checks that, print a warning if suitable, and then `require("./cli")`.

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3370.
