### ISSUE TITLE
Error when moving from local to production with `HH1: You are not inside a Hardhat project on the server`

### ISSUE THREAD

**Issue by alexiskattan** [NomicFoundation/hardhat#3421]
We have the system working in local, but when deploy to server it breaks.  The issue is `HH1: You are not inside a Hardhat project on the server`.  On the serve we are `import { run } from 'hardhat'` and then call `const tx = await run("doThing")`.  We moved everthing from `devDependencies` to `dependencies`, but it still doesn't work.

**Comment by fvictorio** [comment]
@alexiskattan this normally means that you don't have a `hardhat.config.js`. Maybe it's not being pushed for some reason?

If your repo is public, I can take a look.

**Comment by alexiskattan** [comment]
Firstly, thank you.  Secondly, I made a minimal version of the Hardhat and NextJS app that has the same issue.

[https://github.com/alexiskattan/my-app2](https://github.com/alexiskattan/my-app2)

The crux of the issue seems to be when importing `hre` it throws the error `HH1: You are not inside a Hardhat project`
https://github.com/alexiskattan/my-app2/blob/15b8c22a9a3a80829a0eb21bdee991d7336246f9/pages/api/hello.ts#L15

`"hardhat": "^2.12.4"` is in the right dependcies in `package.json` so I'm super not sure what it is not being called when on the server.  It works on local, but when deployed to Vercel it breaks.

Thanks again for looking into it.

**Comment by fvictorio** [comment]
I see. My guess is that Next is bundling your project and that is causing the `hardhat.config.js` file to not be present anymore (either because it's discarded, or because it's being included in the bundle).

I'm not sure what the right fix is here. I guess I would check their docs to see if there's some way to prevent that file from being bundled, or in general how to keep it as part of the project in production.

**Comment by fvictorio** [comment]
Tentatively closing this because I'm not sure if there's something we can do on our side.
