### ISSUE TITLE
getting an EVM compatible network to send type 2 transactions

### ISSUE THREAD

**Issue by tzapu** [NomicFoundation/hardhat#3569]
hello and thank you very much for hardhat.

i am trying to use/send some transactions through file coin's evm compatible layer (json rpc endpoint here) and most stuff works ok.

the biggest issue i have is that when i send a transaction hardhat/ethers is trying to send it as a type 1 tx and it gets rejected by the rpc endpoint which only takes type two txs. 
If i for the tx to be type 2 through overrides it works perfectly, but it s quite tedious with lots and lots of transactions as i need to do them individually.

Is there anything that could and should be done at some level to make sure the network is identified as eip1559 compatible and only type 2 txs are sent? What layer (hardhat/ethers/rpc node?) is that check done at and what is the actual check? 

thanks again

**Comment by fvictorio** [comment]
> What layer (hardhat/ethers/rpc node?) is that check done at and what is the actual check?

If you are using ethers, then ethers is the one that will "decide" which type of transactions to send. But the latest versions of ethers do default to type 2 transactions, unless you include a `gasPrice` field. If you do that, then a type 0 tx will be used.

Closing this because I don't think there's nothing to do on our side.

**Comment by tzapu** [comment]
thanks @fvictorio for pointing me in the right direction
