### ISSUE TITLE
`revertedWith` failed to catch error msg in error object

### ISSUE THREAD

**Issue by shunjizhan** [NomicFoundation/hardhat#3586]
### Version of Hardhat

2.12.5

### What happened?

I migrated from `ethereum-waffle` to hardhat matchers, and previous passing tests are failing. 

This is because the response's shape is
```
{
    "id": 0,
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "some error"
    }
}
```
which can be caught by `ethereum-waffle` (v3.3.4)
https://github.com/TrueFiEng/Waffle/blob/91ac212757cd360b075b4ce12a11cabbf66b8a45/waffle-chai/src/matchers/revertedWith.ts#L28

And hardhat matchers won't either check the `message` key in the error object, or stringily the whole object
https://github.com/NomicFoundation/hardhat/blob/e92b6b7b90032e380d43919b11a0d7a61f093ff6/packages/hardhat-chai-matchers/src/internal/reverted/utils.ts#L29

### Minimal reproduction steps

test `revertedWith` against the error shape mentioned above, it won't pass.
```ts
expect().to.be.revertedWith("some error")
```

### Search terms

revertedWith

**Comment by fvictorio** [comment]
The `revertedWith` implementation in waffle just checks that the error message contains the given string. That's why it was working for you.

The Hardhat chai matchers implementation, on the other hand, actually checks that the transaction reverted because of a revert (like, say, `require(false, "error reason")`) and checks that the given reason string matches exactly the revert reason.

In most scenarios, our implementation is what you really want, and produces way fewer false positives. I think in your case you were running into a "useful" buggy behavior. If you want a similar behavior, you could use [`chai-as-promised`](https://www.chaijs.com/plugins/chai-as-promised/)'s `rejectedWith` matcher, which uses the rejected promise error message.
