### ISSUE TITLE
use config.paths.sources as root path for compilation.

### ISSUE THREAD

**Issue by adjisb** [NomicFoundation/hardhat#3755]
When compiling with hardhat it uses `config.paths.root` as the root of the source code this adds an extra `contracts/` to the source of the contracts (even if `config.paths.sources` is set to `contracts`). Is seems that this problem can be fixed by using `config.paths.sources` instead of `config.paths.root` in the following tasks:

- [TASK_COMPILE_SOLIDITY_GET_SOURCE_NAMES](https://github.com/NomicFoundation/hardhat/blob/2295c04c8fb598932023193ca411307013d44712/packages/hardhat-core/src/builtin-tasks/compile.ts#L144)

- [TASK_COMPILE_SOLIDITY_GET_DEPENDENCY_GRAPH](https://github.com/NomicFoundation/hardhat/blob/2295c04c8fb598932023193ca411307013d44712/packages/hardhat-core/src/builtin-tasks/compile.ts#L193)

This affects the compilation metadata and then the ipfs hash in the bytecode so this change can be problematic, in any case it seems that there is a bug and using  `config.paths.sources`  is the right thing to do.

**Comment by adjisb** [comment]
https://github.com/NomicFoundation/hardhat/pull/3756

**Comment by fvictorio** [comment]
Hi @adjisb. This is by design and changing it would be a huge breaking change. As an example of something that relies on this: the whole directory structure of the `artifacts` depends on this convention.

One of the reasons this is done this way is to tell apart files that are local to your project from files that come from installed libraries.
