### ISSUE TITLE
multiple chained changeTokenBalances matchers do not work

### ISSUE THREAD

**Issue by ZumZoom** [NomicFoundation/hardhat#3776]
### Version of Hardhat

2.13.0

### What happened?

`changeTokenBalances` does not allow to track balances of multiple tokens from single transaction. The snippet in reproduction should fail on first assertion but instead both of them pass.

### Minimal reproduction steps

  ```javascript
  it('track multiple changeTokenBalances', async function () {
      const { dai } = await loadFixture(initContracts);
      await expect(dai.transfer(addr1.address, ether('0.1')))
          .to.changeTokenBalances(dai, [addr, addr1], [ether('-0.2'), ether('0.2')])
          .to.changeTokenBalances(dai, [addr, addr1], [ether('-0.1'), ether('0.1')]);
  });
  ```
  
  ### Search terms

chai-matchers

**Comment by ZumZoom** [comment]
This code works though.

```javascript
it.('track multiple changeTokenBalances', async function () {
    const { dai } = await loadFixture(initContracts);
    const tx = dai.transfer(addr1.address, ether('0.1'));
    await expect(tx).to.changeTokenBalances(dai, [addr, addr1], [ether('-0.1'), ether('0.1')]);
    await expect(tx).to.changeTokenBalances(dai, [addr, addr1], [ether('-0.1'), ether('0.1')]);
});
```

Closing the issue then.

**Comment by k06a** [comment]
Let's try to fix this?

**Comment by fvictorio** [comment]
Hi, sorry for not responding here before. I think we should start by forbidding chaining operators, since that doesn't really work right now and it's misleading to not throw when a user does that. Issue https://github.com/NomicFoundation/hardhat/issues/3667 tracks that.

After that we might consider enabling chaining as a separate feature request, but sadly chai makes that pretty hard.

I'm going to close this issue in favor of #3667.
