### ISSUE TITLE
solidity-coverage not running preprocess in hardhat config (remappings)

### ISSUE THREAD

**Issue by victormer** [NomicFoundation/hardhat#3816]
### Version of Hardhat

2.12.6

### What happened?

I have a preprocess function processing a remapping for imports. This works perfectly fine when running `hardhat compile` but it fails when running `hardhat coverage`. It seems like solidity-coverage plugin is working on files before preprocessing them or not even taking preprocess configuration into account.

I tried using `.solcover.js` for applying the same preprocess function but I was not able to do it.

### Minimal reproduction steps

1. Get a repository of contracts with `solidity-coverage` plugin

2. Create remappings.txt with remappings from your libraries to whatever you want like: `uniswapv2-core/=lib/v2-core/contracts/`

3. Apply a remapping function like this example in hardhat config preprocess:

```
function getRemappings() {
    return fs
        .readFileSync("remappings.txt", "utf8")
        .split("\n")
        .filter(Boolean)
        .map((line) => line.trim().split("="));
}

// In HardhatUserConfig
preprocess: {
  eachLine: (hre: any) => ({
    transform: (line: string) => {
      if (line.match(/^\s*import /i)) {
        getRemappings().forEach(([find, replace]) => {
        if (line.match('"' + find)) {
            line = line.replace('"' + find, '"' + replace);
        }
        });
      }
      return line;
    }
  })
}
```
4. Run `hardhat compile` (Should work fine)
5. Run `hardhat coverage` (Fails)

### Search terms

solidity-coverage preprocess config remapping

**Comment by fvictorio** [comment]
A couple of things here:

- This seems to be a solidity-coverage and/or hardhat-preprocessor issue, but both of those plugins are community plugins. This issue tracker is used for Hardhat itself and our official plugins.
- Are you using preprocessor to be able to use Hardhat with Foundry? If that's the case, take a look at [our guide](https://hardhat.org/hardhat-runner/docs/advanced/hardhat-and-foundry) on how to use both tools together.

Tentatively closing, I'll re-open if this turns out to be a problem in Hardhat itself, but seems unlikely.

**Comment by tmavroeid** [comment]
I had the same issue and managed to solve it by adding a task in my hardhat project:
```
import { task } from 'hardhat/config';
import { TASK_PREPROCESS } from 'hardhat-preprocessor';

task('coverage-updated', 'Run coverage after running pre-process task').setAction(
  async function (args, env) {
    await env.run(TASK_PREPROCESS);
    await env.run('coverage');
  }
);
```
and then import the task into the `hardhat.config.ts`
