### ISSUE TITLE
Hardhat doesnt seem to be compiling on vs code 

### ISSUE THREAD

**Issue by boxingcoder00** [NomicFoundation/hardhat#3817]
Hardhat doesnt seem to be compiling on vs code unlike my friends computer. I have all the same downloaded and set up but doesnt work it seems i keep getting the picture below .(still a nooby) 
![wont compile](https://user-images.githubusercontent.com/111091683/230232640-dcd382dc-97f1-471e-a78d-34aabff9786b.png)

**Comment by Saty248** [comment]
@boxingcoder00 have you tried to install hardhat in a different directory and still getting the same result?

**Comment by boxingcoder00** [comment]
> @boxingcoder00 have you tried to install hardhat in a different directory and still getting the same result?

same result

**Comment by boxingcoder00** [comment]
frustrating as once again i try and the above comes up to create a project instead of compiling and get the folder i need

**Comment by boxingcoder00** [comment]
the artifacts folder doesnt show up

**Comment by Saty248** [comment]
@boxingcoder00  I also use hardhat on vscode bt this issue didnt happen to me.

**Comment by Saty248** [comment]
i would recommend that you follow the steps given in the docs thoroughly while installing the and setting up hardhat.

**Comment by boxingcoder00** [comment]
Yea ill go thru them thanks for helping

**Comment by Memnon-ofol** [comment]
I try to npx install and instead of getting the command line HARDHAT interface I get this:
Hardhat version 2.13.1

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

GLOBAL OPTIONS:

  --config              A Hardhat config file.
  --emoji               Use emoji in messages.
  --flamegraph          Generate a flamegraph of your Hardhat tasks
  --help                Shows this message, or a task's help if its name is provided    
  --max-memory          The maximum amount of memory that Hardhat can use.
  --network             The network to connect to.
  --show-stack-traces   Show stack traces (always enabled on CI servers).
  --tsconfig            A TypeScript config file.
  --typecheck           Enable TypeScript type-checking of your scripts/tests
  --verbose             Enables Hardhat verbose logging
  --version             Shows hardhat's version.


AVAILABLE TASKS:

  check         Check whatever you need
  clean         Clears the cache and deletes all artifacts
  compile       Compiles the entire project, building all artifacts
  console       Opens a hardhat console
  flatten       Flattens and prints contracts and their dependencies. If no file is passed, all the contracts in the project will be flattened.
  help          Prints this message
  node          Starts a JSON-RPC server on top of Hardhat Network
  run           Runs a user-defined script after compiling the project
  test          Runs mocha tests

To get help for a specific task run: npx hardhat help [task]

Ive looked around a few place but the best info I got was to try npx install --verbose which I can't see how that helps me.

**Comment by boxingcoder00** [comment]
![help2](https://user-images.githubusercontent.com/111091683/231615459-ff5f2adb-be54-40a0-b7e9-4ad31285c776.png)

**Comment by boxingcoder00** [comment]
I get this now

**Comment by fvictorio** [comment]
There are a lot of things going on here. Please keep issues focused, otherwise it's super hard to help.

The last error, about ESM, has the explanation and the solution in the message. If you have no idea what ESM and CJS means, then just remove the `"type": "module"` entry in your package.json.

@Memnon-ofol with respect to that problem, see [this](https://hackmd.io/@fvictorio/a-hardhat-faq#npx-hardhat-doesn%E2%80%99t-initialize-a-project).

I'm going to close this now. Remember that the issue tracker is meant to be used for bugs or feature requests. If you have questions, open a [discussion](https://github.com/NomicFoundation/hardhat/discussions). But please make an effort make clear, focused questions, and include the relevant context.
