### ISSUE TITLE
How can i test this method? aka How to change chain in the middle of a test?

### ISSUE THREAD

**Issue by migoldfinger** [NomicFoundation/hardhat#3859]
How can I test the else path of this method?
I did not find a way to change the chainid during an test.
```
function DOMAIN_SEPARATOR() public view override returns (bytes32) {
		return
			block.chainid == _domainSeperatorChainId
				? _domainSeperator
				: _calculateDomainSeparator(block.chainid);
	}
```
I am just curious, it is not that important. but 100% test coverage would be awesome ^^.

**Comment by fvictorio** [comment]
This is not super easy to do due to https://github.com/NomicFoundation/hardhat/issues/3074.

The best thing that comes to mind is this. First, in your `hardhat.config.js`, configure the chain id with something like this:

```
networks: {
  hardhat: {
    chainId: process.env.CHAIN_ID ? Number(process.env.CHAIN_ID) : 31337
```

Then you can have a different test script that is something like:

```
"test:different-chain-id": "CHAIN_ID=31338 hardhat test test/some-test-that-uses-chain-id.js"
```

I'm using 31337 and 31338 as examples here. Also, I'm passing a single file to the test because I guess most tests won't be affected by a different chain id.

A problem with this though is that it would mean two different runs, so your coverage report will still not cover that branch.

I know it's a shitty solution, I hope we can get #3074 fixed somewhat soon, but it depends on a huge refactor right now.
