### ISSUE TITLE
Can not run npx hardhat coverage

### ISSUE THREAD

**Issue by dtnwen** [NomicFoundation/hardhat#3892]
I run `npx hardhat coverage` and have this error. It doesn't make sense at all. The contract works totally fine. I already import `require("@nomicfoundation/hardhat-toolbox");` in config file.

![image](https://user-images.githubusercontent.com/65008502/235660922-18fe04b4-88b9-4c14-85b0-4d3a65870cfe.png)

**Comment by fvictorio** [comment]
@dtnwen that's a compilation error here. There are two possibilities:

- You just have a compilation error in your contract (but I assume that's not the case)
- `solidity-coverage` generates a compilation error during instrumentation. If that's what's going on, you should open an issue in [their repo](https://github.com/sc-forks/solidity-coverage).

Closing because in both cases there's nothing we can do on our side.
