### ISSUE TITLE
Expose vm 'step' hooks for Hardhat Network

### ISSUE THREAD

**Issue by cgewecke** [NomicFoundation/hardhat#391]
Hi @alcuadrado - just opening per your suggestion that it might be possible. In a note you proposed an experimental API

> Maybe `__experimental__attachBuidlerVMListeners(vm => { ... })`

Do you have any more thoughts about this?

**Comment by alcuadrado** [comment]
Hey Chris! Thanks for opening this issue so we can keep track of this. 

I've been thinking more about it, and I think that having a method to let you attach to the `step` event is the way to go. 

We also talked about doing this by wrapping the provider and accessing its vm, but that would bring lots of complications. The main issue is that you'd need to find a way to distinguishing between the vm running because of gas estimations and because of actual txs/calls. By registering the event listener through Buidler, we can make sure that it isn't fired for gas estimations.

I wonder if some way of removing the listener is needed. What do you think?

Also, I still think that this should be considered experimental for now. It would couple Buidler's API to the `ethereumjs-vm`'s one, and I don't want to take that decision lightly, but I do want to offer you the necessary capabilities for `solidity-coverage` and `eth-gas-reporter` asap.

**Comment by cgewecke** [comment]
Thanks @alcuadrado!

> By registering the event listener through Buidler, we can make sure that it isn't fired for gas estimations.

Have noticed that there's a similar duplication in truffle-contract when the reason is fetched on tx error as well. In that case the tx is replayed as a call to extract the data. For coverage, this has worried me a little less - it affects how many hits are registered for each line. But yes the repetitions are not obvious to the end user of an API like this and would be a problem if you were trying to track gas via the step or something.

> I wonder if some way of removing the listener is needed. What do you think?

I'm just attaching once ... actually what is your view of this? Are there cases where one might set up this listener repeatedly, or perhaps have a problem exiting because a listener was attached? 

> I still think that this should be considered experimental for now.

Completely fine. Would describe the way I'm currently attaching to the vm at ganache as 'illegal' so experimental is a big improvement. Very happy to trial anything you come up with :)

**Comment by alcuadrado** [comment]
> I'm just attaching once ... actually what is your view of this? Are there cases where one might set up this listener repeatedly, or perhaps have a problem exiting because a listener was attached?

I believe that keeping the listener attached won't lead to any problem. It shouldn't prevent Buidler from exiting.

> Have noticed that there's a similar duplication in truffle-contract when the reason is fetched on tx error as well. In that case the tx is replayed as a call to extract the data. For coverage, this has worried me a little less - it affects how many hits are registered for each line. But yes the repetitions are not obvious to the end user of an API like this and would be a problem if you were trying to track gas via the step or something.

Maybe instead of just giving the `step` info, I can also provide the info of the RPC call that triggered that execution. Would this work?

I could also add oncall and ontx events, and pass you one of [these traces](https://github.com/nomiclabs/buidler/blob/master/packages/buidler-core/src/internal/buidler-evm/stack-traces/message-trace.ts). Those have all the needed info, but using them may require some extra work compared to just using `step`.

**Comment by cgewecke** [comment]
>  I can also provide the info of the RPC call that triggered that execution

Yes! I think that context info might be very useful in general / solve coverage's problem specifically.

> I could also add oncall and ontx events, and pass you one of these traces.

Atm at the gas reporter, the data collected is less granular than the step. The main speed optimization I've thought about involves observing the provider 
+ *as it sends*, to collect the transaction input (fn sig) and destination address
+ *as the receipt resolves*, to collect the gas used (and contractAddress if present)

This would allow the reporter to skip a large number of synchronous secondary calls to fetch the block, fetch each tx, etc etc which slow everything down ~100%. 

Are those stages possible to express as events?

**Comment by alcuadrado** [comment]
> Yes! I think that context info might be very useful in general / solve coverage's problem specifically.

Good to know. I'll think more about this, but it's doable.

> * _as it sends_, to collect the transaction input (fn sig) and destination address

This could be implemented by wrapping the provider, right? Maybe that's a better way of doing it.

> * _as the receipt resolves_, to collect the gas used (and contractAddress if present)

If the provider supports notifications you could implement this when a new block notification is fired, right?

I'm a little hesitant about adding an "on mined/receipt" event, as that would make less sense in a more realistic context because of reorgs, and one of the mid-term plans is to add apis/flags to Buidler EVM to simulate reorgs and other network disturbances. I guess smart contract devs won't use them, but they are pretty important to test dapps.

**Comment by cgewecke** [comment]
> This could be implemented by wrapping the provider, right? Maybe that's a better way of doing it.

Agree! Sounds good to me.

> I'm a little hesitant about adding an "on mined/receipt" event, as that would make less sense in a more realistic context because of reorgs, and one of the mid-term plans is to add apis/flags to Buidler EVM to simulate reorgs and other network disturbances. I guess smart contract devs won't use them, but they are pretty important to test dapps.

Yes, that seems more important to me as well. I think wrapping is the best solution on my end.

**Comment by fvictorio** [comment]
This is probably not relevant anymore, and it won't be doable after rethnet anyway.
