### ISSUE TITLE
noCompile flag for task

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat#4029]
### Describe the feature

seems currently noCompile can only be used in script but not in task.

**Comment by GopherJ** [comment]
I tried:

```
task("deploy:all", "Deploy all contracts").setAction(async (_, DRE) => {
  await DRE.run("set-DRE", {noCompile: true});
  //for test_only mode we run each test in a live hardhat network without redeploy
```

but it doesn't seem to work

**Comment by GopherJ** [comment]
this caused a big issue in zksync development as zksolc compiles super slow ~ 10mins

**Comment by fvictorio** [comment]
Sorry, I don't understand what this issue is about. Can you explain what you are doing, what you tried, and what's the problem you are getting?

**Comment by GopherJ** [comment]
hi @fvictorio I'm experimenting with hardhat-zksync, it compiles slowly and the cache seems not working, so I try to use `--no-compile` flag to not recompile again and again.

However, `--no-compile` can only be added to script, which means after `npx hardhat run xxx` but it cannot be added while executing a task via `npx hardhat task1::subtask1`

**Comment by fvictorio** [comment]
Hey @GopherJ, `--no-compile` is a custom flag of the build-in `test` and `run` tasks. When you define a custom task and run it, Hardhat won't compile. If you want that to happen you'll have to do it explicitly:

```js
task("foo", async (args, hre) => {
  await hre.run("compile")

  // your task definition
})
```

and if you want to add a no compile flag task, you also have to do it yourself:

```js
task("foo")
  .setFlag("noCompile")
  .setAction(async (args, hre) => {
  if (!args.noCompile) {
    await hre.run("compile")
  }

  // your task definition
})
```

I think your problem is that you want to pass `--no-compile` to all your tasks, but some of them don't have that flag and therefore they throw an error.

I'm going to tentatively close this because I don't think there's a problem on our side, but I'll re-open if there is.
