### ISSUE TITLE
Latest version of Hardhat doesn't work with solidity-coverage

### ISSUE THREAD

**Issue by wattsyart** [NomicFoundation/hardhat#4063]
### Version of Hardhat

2.16.0

### What happened?

Starting a new example JavaScript project results in failed `solidity-coverage`.

### Minimal reproduction steps

- `npx hardhat`
- Create a JavaScript project
- `npm install --save-dev "hardhat@^2.16.0" "@nomicfoundation/hardhat-toolbox@^3.0.0"`
- `npx hardhat coverage`

"Error in plugin solidity-coverage: TypeError: provider.send is not a function"

### Search terms

solidity-coverage TypeError

**Comment by Prcentos** [comment]
Yeah, I have encountered the same question

**Comment by fvictorio** [comment]
Hi, yes, `solidity-coverage` relies on some internal APIs that we changed in the latest release.

I sent a PR some weeks ago preparing it for this new version: https://github.com/sc-forks/solidity-coverage/pull/796 But the fix is not published yet.

Sorry about that! Hopefuly @cgewecke releases a new version soon.

**Comment by Prcentos** [comment]
Version 0.8.3 of solidity-coverage have resolve this problem
