### ISSUE TITLE
Use ethersjs v6 AddressLike type in hardhat-chai-matchers

### ISSUE THREAD

**Issue by RenanSouza2** [NomicFoundation/hardhat#4097]
### Describe the feature

ethersjs v6 implements a AddressLike type that improoves the UX by allowing to pass an signer or contract object where an address is expected

hardhat-chai-matchers still expects a string for an address so I suggest using the same treatment,

I thought this was implemented in the ethers.io project so I fist opened this issue: https://github.com/ethers-io/ethers.js/issues/4191

**Comment by fvictorio** [comment]
Hi @RenanSouza2, which matchers do you think should support AddressLike values? Some examples would be great.

We accept contracts right now, but maybe this is about expanding those types to allow more general Addressable things.

**Comment by RenanSouza2** [comment]
In this repository I wrote some examples: https://github.com/RenanSouza2/chai-matchers-example/blob/main/test/Lock.ts

the examples I would like are in comparing returned addresses from contracts to signers

and in the 'withArgs' of events matchers and revertedWithCustomError

**Comment by frangio** [comment]
> We accept contracts right now

Where is this implemented? I can't find it in the code.

**Comment by fvictorio** [comment]
@RenanSouza2 thanks for the examples. I agree that having those in the `.withArgs` would be super nice. For the equality matchers is sadly not possible in the general case, because `getAddress` is async. We could maybe do it with `.target` but that doesn't work in some cases.

@frangio for example, you can do this:

```js
await expect(foo.inc()).to.changeEtherBalance(foo, 0)
```

or this:

```js
await expect(foo.inc()).to.changeEtherBalance(await foo.getAddress(), 0)
```

That's implemented [here](https://github.com/NomicFoundation/hardhat/blob/a207463f2bd1d533c9d93538c60d120beb697bf6/packages/hardhat-chai-matchers/src/internal/misc/account.ts#L7).

**Comment by Amxx** [comment]
#4449 should fix that issue. Open to feedback !
