### ISSUE TITLE
Estimated feePerGas can be zero

### ISSUE THREAD

**Issue by aathan** [NomicFoundation/hardhat#4136]
### Version of Hardhat

2.16.1

### What happened?

hardhat makes calls like: `{"jsonrpc":"2.0","method":"eth_feeHistory","params":["0x1","latest",[50]],"id":9}`
If the fork environment called has a base fee set to `1` , or for any other reason, the response may be:
`{"jsonrpc":"2.0","id":9,"result":{"baseFeePerGas":["0x1","0x0"],"gasUsedRatio":[0.0],"oldestBlock":"0x1efea03","reward":[["0x0"]]}}`

The next eth_sendTransaction by hardhat contained: `"maxFeePerGas":"0x0","maxPriorityFeePerGas":"0x0"}]`

Hardhat should probably not ever send transactions with 0 for these fields. The word "probably" may be debatable, but do we really expect any chain that is allowing free transactions?

### Minimal reproduction steps

Send multiple transactions of any kind to an `anvil --base-fee 1` node.

**Comment by fvictorio** [comment]
I'm not sure I understand. The way I see it, Hardhat lets you set the base fee to 0 (this is useful in many testing scenarios), and if the base fee is 0 then that's what `eth_feeHistory` will return.

**Comment by fvictorio** [comment]
> Just for my edification and so that we are on the same page, can you describe how this is useful in many testing scenarios -- assuming you mean in some way beyond the trivial "I don't want to spend down my fee currency during tests"?

Sending transactions from impersonated accounts without having to add funds to them is one. Some people also use this to assert how the balance of an account changed during a tx, although that's better done with the [balance change matchers](https://hardhat.org/hardhat-chai-matchers/docs/reference#balance-change).

> I guess I'm just making the simple point that this is a bit of a weird value, and since hardhat is _calculating the fee_ by delegating that calculation to the chain provider via a percentile, if a production dapp gets back zero, that's very likely a misconfiguration (maybe DNS is not pointed correctly and ended up giving you the test chain, whatever).

I agree in principle, but this is a design question: if I can possibly detect that there's a problem, even if it's in an external component, should I do it an report a proper message? In some cases the answer is undoubtedly yes (for example, I think we do this when people fork non-archive nodes). In other cases, the answer is no or not yet, mainly because any change like this takes time and adds complexity.

In this particular case I'm inclined to say no. If the remote node returns a wrong value, then the user should have enough information to figure out what's the problem. Hardhat would only be the middle man in this case.

If it was the case that provider often return a wrong value for some preventable reason, and a lot of users run into that problem, I would probably change my mind.

**Comment by fvictorio** [comment]
Tentatively closing this.
