### ISSUE TITLE
@nomicfoundation/hardhat-ethers import still required with toolbox 3 ?

### ISSUE THREAD

**Issue by SvenMeyer** [NomicFoundation/hardhat#4153]
### Version of Hardhat

2.17.0

### What happened?

Documentation say that if I have
`import "@nomicfoundation/hardhat-toolbox";`
I do not need `@nomicfoundation/hardhat-ethers`
[https://hardhat.org/hardhat-runner/docs/guides/migrating-from-hardhat-waffle#migrating-to-hardhat-toolbox](https://hardhat.org/hardhat-runner/docs/guides/migrating-from-hardhat-waffle#migrating-to-hardhat-toolbox)

### Minimal reproduction steps

However when creating a new typescript hardhat template it is included in `package.json`
Also `ethers.getSigners();` gives me an error with `import { ethers } from "hardhat";` in place.

**Comment by SvenMeyer** [comment]
Which imports are still needed now with the toolbox 3 ?

```json
{
  "name": "hardhat-template",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@nomicfoundation/hardhat-chai-matchers": "^2.0.0",
    "@nomicfoundation/hardhat-ethers": "^3.0.0",
    "@nomicfoundation/hardhat-network-helpers": "^1.0.0",
    "@nomicfoundation/hardhat-toolbox": "^3.0.0",
    "@nomicfoundation/hardhat-verify": "^1.0.0",
    "@typechain/ethers-v6": "^0.4.0",
    "@typechain/hardhat": "^8.0.0",
    "@types/chai": "^4.2.0",
    "@types/mocha": ">=9.1.0",
    "@types/node": ">=16.0.0",
    "chai": "^4.2.0",
    "ethers": "^6.4.0",
    "hardhat": "^2.17.0",
    "hardhat-gas-reporter": "^1.0.8",
    "solidity-coverage": "^0.8.0",
    "ts-node": ">=8.0.0",
    "typechain": "^8.1.0",
    "typescript": ">=4.5.0"
  }
}
```

**Comment by SvenMeyer** [comment]
For me (it looks like as if) it works (at least) without these packages
```
hardhat-gas-reporter
solidity-coverage
@typechain/hardhat
```

`@nomicfoundation/hardhat-verify` not yet tested

**Comment by clauBv23** [comment]
It might be due to your npm version being lower than 7.


When using npm 6 [in the link you shared](https://hardhat.org/hardhat-runner/docs/guides/migrating-from-hardhat-waffle#migrating-to-hardhat-toolbox) says that yo will need toolsbox peer dependencies and `@nomicfoundation/hardhat-ethers` is one of them 

> Then you need to install the Toolbox. **_If you are using yarn or an old version of npm, you'll also have to install some other packages (the peer dependencies of the Toolbox)_**.


try upgrading your npm version.

**Comment by SvenMeyer** [comment]
@clauBv23 I am using `pnpm`
```
$ pnpm --version
8.6.7
```

**Comment by fvictorio** [comment]
I think there are two different things here. One is about imports, and this is independent of the package manager: if you are requiring/importing `@nomicfoundation/hardhat-toolbox`, then you don't need to import any of the plugins that it includes. If you get a typescript error, then that might be a configuration problem (normally the `tsconfig.json` file has some issue).

Then, with respect to package managers: I think only npm 7+ automatically installs peer dependencies. AFAIK pnpm does too but it's an opt-in option that you have to enable with `pnpm config set auto-install-peers true`.

@SvenMeyer If that doesn't answer your question, I'm gonna need you to be more specific about what your problem is and, if possible, to create a reproduction example.

**Comment by crush0x** [comment]
Just to confirm here, the issue does seem to be related to pnpm not installing peer dependencies automatically. I had the same issue as OP when creating a new Hardhat project, with ethers.getSigners imported as { ethers } from "hardhat". 

I nuked my node_modules and reinstalled with npm (v9) and the issue disappeared. There are ways to tell pnpm to auto-install peer dependencies but it might be best just to stick with npm.

**Comment by fvictorio** [comment]
@crush0x out of curiosity, which version of pnpm are you using? Because the docs [seem to suggest](https://pnpm.io/npmrc#auto-install-peers) that peer dependencies are installed automatically.
