### ISSUE TITLE
HardHat AutoGasManager's fee estimation breaks on low-traffic chains

### ISSUE THREAD

**Issue by roberto-bayardo** [NomicFoundation/hardhat#4190]
### Version of Hardhat

2.17.0

### What happened?

Hardhat's `AutomaticGasProvider` seems to use its own algorithm based on eth_FeeHistory to compute maxPriorityFeePerGas and MaxFeePerGas. When the most recent block is empty, the code ends up returning "0" for maxPriorityFeePerGas, producing a transaction that will be immediately rejected by almost all node transaction pools with "transaction underpriced" errors.

We looked into this because of several reports of this error from people who are following the Base contract deployment guide [here](https://docs.base.org/guides/deploy-smart-contracts). I imagine this issue also arises on other development / testnet chains where traffic is low.

Obviously one can work around this by specifying your own gas price in the hardhat user config (we're updating or docs right now to do this), but better for auto-estimation to always work.

To that end, one option would be to leverage the eth_maxPriorityFeePerGas RPC method to get the node-computed estimate. These algorithms are already well tuned and more likely to do the right thing than any roll-your-own approach.  A simpler option would be to just hard-code a non-trivial minimum on the value always suggested (e.g. .1 gwei).

### Minimal reproduction steps

Use hardhat to submit a transaction to a low-traffic chain (e.g. a devnet) when configured to use the "auto" gas price mode. If the current block is empty the transaction will fail with "transaction underpriced".  Some example output containing additional instrumentation demonstrating the failure:

```
fee history: {
  baseFeePerGas: [ '0x32', '0x32' ],
  gasUsedRatio: [ 0.0015637666666666666 ],
  oldestBlock: '0x17d47a',
  reward: [ [ '0x0' ] ]
}
suggesteEip1559Values { maxFeePerGas: 63n, maxPriorityFeePerGas: 0n }

Result: 

ProviderError: transaction underpriced
    at HttpProvider.request (/Users/bayardo/tmp/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HardhatEthersSigner.sendTransaction (/Users/bayardo/tmp/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async ContractFactory.deploy (/Users/bayardo/tmp/node_modules/ethers/src.ts/contract/factory.ts:112:22)
    at async main (/Users/bayardo/tmp/scripts/deploy.ts:4:15)
```

**Comment by fvictorio** [comment]
Thank you @roberto-bayardo for the detailed information, we'll look into this.

**Comment by Saty248** [comment]
@fvictorio .. I would like to contribute to this issue..but right now all i can think of is setting a default non-trivial minimum on the value as suggested.. Any ideas coming to your mind to solve this issue? maybe i can try those ..

**Comment by fvictorio** [comment]
Hey @Saty248, sorry for not responding before. This issue is a bit involved, so someone from the team should tackle it.

This will need some experimentation to double-check that using `eth_maxPriorityFeePerGas` fixes the problem. But this is easy to do: we should reproduce the problem with a chain that has that method (Hardhat currently doesn't) and then change Hardhat to use that method first when estimating the gas price. If that fails, we then fall back to the current approach. We should do this with throwaway code to validate the approach; later we can implement it properly.

If that indeed works (and it probably will) we should:
- [ ] Add the `eth_maxPriorityFeePerGas` method to Hardhat. It doesn't make sense to rely on a method that we don't support. I'm not sure what's the correct implementation here. We should check what geth does and see if that works for us.
- [ ] Add tests for this method.
- [ ] Add this method to the docs.
- [ ] A test that reproduces the bug (_before_ implementing the solution)
- [ ] Implement the solution explained in the previous paragraph.

**Comment by shoenseiwaso** [comment]
We're also hitting this issue extensively on Base Goerli Testnet, which appears to be given the very low number of transactions on this testnet and the different way that Optimism (i.e. Base) estimates gas. It would be great to have it addressed. It basically makes Hardhat unusable on Base.

**Comment by kalote** [comment]
We're hitting the same kind of issue on LUKSO testnet, and we will love to see the `eth_maxPriorityFeePerGas` used before the `eth_feeHistory` to calculate the maxPriorityFeePerGas and MaxFeePerGas values. Any plan to integrate it in your next release? 🙏🏻🙏🏻🙏🏻

**Comment by kev-techi** [comment]
At least a dummy implementation that returns a value we can ignore for the moment. This makes it currently impossible to dev locally without making extensive modifications to the code base.

**Comment by fvictorio** [comment]
Hi everyone, we just released a new version of Hardhat that should fix this problem, or at least make it less likely to happen. Please try it out and let us know if you are still running into issues (or not!).
