### ISSUE TITLE
regression causing all contracts to be uploaded during verification

### ISSUE THREAD

**Issue by hexpaydaydev** [NomicFoundation/hardhat#4431]
### Version of Hardhat

2.17.2

### What happened?

all contracts, whether or not they were linked to targeted contract, were uploaded to etherscan + blockscout

examples:

https://scan.pulsechain.com/address/0x209b1C66cB0Ea99DC2d4Ad13C35859DD1c258988/contracts#address-tabs

https://etherscan.io/address/0x209b1C66cB0Ea99DC2d4Ad13C35859DD1c258988#code

see: contracts/test/IMulticall.sol as an example

### Minimal reproduction steps

1. create a hardhat repo
2. create 2, unlinked contracts
3. compile
4. deploy
5. verify
6. check

**Comment by hexpaydaydev** [comment]
similar to https://github.com/NomicFoundation/hardhat/issues/804

**Comment by fvictorio** [comment]
Hi @hexpaydaydev, I did exactly what you said (I created a project with two unrelated contracts and deployed and verified one of them) and only one of the files was verified, which is the expected behavior.

I'm tentatively closing this, but I'm happy to re-open it if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
