### ISSUE TITLE
Hardhat-network-helpers loadFixture is not working when running coverage

### ISSUE THREAD

**Issue by Amxx** [NomicFoundation/hardhat#4474]
### Version of Hardhat

2.18.0

### What happened?

See https://github.com/sc-forks/solidity-coverage/issues/819

### Minimal reproduction steps

See https://github.com/sc-forks/solidity-coverage/issues/819

### Search terms

chai fixture coverage

**Comment by cgewecke** [comment]
The companion issue for this at solidity-coverage has been resolved & the test helpers seem to work ok. See https://github.com/sc-forks/solidity-coverage/issues/819#issuecomment-1762963679 for details.

**Comment by fvictorio** [comment]
Sorry, I'm not sure if there's something we need to do here?

**Comment by Amxx** [comment]
> The companion issue for this at solidity-coverage has been resolved & the test helpers seem to work ok. 

I would disagree with that. Solidity-coverage not properly handling the hardhat env extension is a major drawback that can't simply be ignored.
Not sure anything should be done at the hardhat level though.

**Comment by cgewecke** [comment]
>I would disagree with that. Solidity-coverage not properly handling the hardhat env extension is a major drawback that can't simply be ignored.

For more context I think the problem was caused by: 
+ using extendEnv to [cache signers from the initial provider instantiated by hardhat][1] 
+ solidity-coverage creating a new provider (and losing a relationship to the cached accounts)  

It's kind of related to  #1374 and #3491 although there are places in Hardhat itself (notably hardhat_reset) where the provider is recreated and it's possible doing this kind of stuff in extendEnv would run into trouble there too? Not certain. 

Ideally the coverage tool would be entirely passive, rely on source-maps & a tracer api, and never touch the provider. This is difficult to get right though (for example, see [Foundry coverage issues][2]

[1]: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4657/commits/74bab8140dececbb72b827ca8fa75e96437c9f49
[2]: https://github.com/foundry-rs/foundry/issues?page=2&q=coverage
