### ISSUE TITLE
ProviderError: missing trie node [string] (path ) <nil>

### ISSUE THREAD

**Issue by joelamouche** [NomicFoundation/hardhat#4519]
### Version of Hardhat

^2.18.1

### What happened?

I am forking mumbai, using `hardhat node` and fork config, to run tests and I randomly get this error:

`ProviderError: missing trie node cd415b780637a9866aa655a8e23ff7b2e2695086783c91e7a8fc00020bc43544 (path ) <nil>`

According to this: https://ethereum.stackexchange.com/questions/149254/using-hardhat-to-fork-a-node-but-getting-missing-trie-node/155695?noredirect=1#comment172491_155695 , it could be caused by the fork being outdated after a while. 

How do I avoid this? 

### Minimal reproduction steps

1. Fork mumbai with hardhat node and 
hardhat: {
      forking: {
        url: `${process.env.ALCHEMY_MUMBAI_URL}`,
      },
    },
2. Run tests at least 5/10mn after the node was started

**Comment by fvictorio** [comment]
This happens because you are not using an archive node. Non-archive nodes drop information of old blocks after a while. Hardhat forks from the latest block number at the time it's run, and then continues fetching state data from that block, so you eventually are asking information about a block whose historical information was dropped.
