### ISSUE TITLE
Support anvil on hardhat-network-helpers

### ISSUE THREAD

**Issue by tmigone** [NomicFoundation/hardhat#4589]
### Describe the feature

It would be useful if the network helpers would support running on anvil. 

The `anvil_*` namespace is an alias for `hardhat_*` in the anvil node, so hardhat's custom methods should work. However the network helpers all check via `getHardhatProvider` that they are being ran on a hardhat network and error out if they are not (https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-network-helpers/src/utils.ts#L40).

I understand if you don't want to support/test on anvil, in which case having a way of bypassing the `checkIfHardhatNetwork` should suffice for people interested in using the helpers on anvil while not adding too much burden on the hardhat team.

**Comment by fvictorio** [comment]
I don't see any reason not to support it, and it should be an easy change :+1:

**Comment by fvictorio** [comment]
From what I can tell, it should be enough to:

- Rename `checkIfHardhatNetwork` to something like `checkIfDevelopmentNetwork`
- Check if the result of `web3_version` *either* starts with `hardhatnetwork` or with `anvil`

I'm also ok with making this change without tests, because we don't currently have them for this method, and doing it would imply a level of mocking that doesn't seem worth it to me.

**Comment by tmigone** [comment]
I can help with a PR then, it seems super straightforward

**Comment by fvictorio** [comment]
Sure, feel free to send one!

**Comment by tmigone** [comment]
Done here: https://github.com/NomicFoundation/hardhat/pull/4591
