### ISSUE TITLE
chai@5 support  in @nomicfoundation/hardhat-chai-matchers package

### ISSUE THREAD

**Issue by Mantas-M** [NomicFoundation/hardhat#4789]
### Describe the feature

Chai released a new breaking version, and the [current docs](https://www.npmjs.com/package/@nomicfoundation/hardhat-chai-matchers) do not specify which version you need to install.

With this version, compilation does not work and gives a HH19 error
`Error HH19: Your project is an ESM project (you have "type": "module" set in your package.json) but your Hardhat config file uses the .js extension.`

It would be beneficial to support the latest version of the testing library

### Search terms

chai chai5 hardhat-chai-matchers

**Comment by schaable** [comment]
Hi @Mantas-M, Hardhat version 2.x with TypeScript does not support ESM packages. If you're interested in trying `chai@5`, you can enable the experimental ESM support as described in this thread: [Hardhat Issue #3385](https://github.com/NomicFoundation/hardhat/issues/3385#issuecomment-1841380253). Otherwise, for compatibility with your current setup, you should install `chai@4`, following the installation instructions in the documentation you referenced.
