### ISSUE TITLE
@nomicfoundation/hardhat-chai-matchers fails to decode revert message when method is called indirectly

### ISSUE THREAD

**Issue by n0thingness** [NomicFoundation/hardhat#4808]
### Version of Hardhat

2.19.5

### What happened?

Hardhat Chai Matchers fails to decode the revert message when the method is called indirectly via a `call` from another contract.

### Minimal reproduction steps

https://github.com/n0thingness/hardhat-chai-matchers-decoding-error

Please pull the repo and run `npm install; npx hardhat test;`

### Search terms

hardhat chai matchers decoding error abi deferred

**Comment by ChristopherDedominici** [comment]
Hi @n0thingness , thanks for reporting this. I'll take a look

**Comment by ChristopherDedominici** [comment]
Hi @n0thingness, I took a look at the issue. I managed to reproduce it, but the problem is not with the package @nomicfoundation/hardhat-chai-matchers. The reason why the error is happening is because the code in the file `Caller.sol` attempts to use `string(result)` directly as the error message, so the assertion is acting as expected.

```sol
(bool ok, bytes memory result) = target.call (data)s
require(ok, string(result));
```

If the result contains non-string data, especially when the call fails (exactly your case), it may have an unexpected behavior, but it's still correct.
What you're trying to achieve is quite complex, because direct propagation of the callee's return data can't be done with `require`. The reason is that `require` takes a string and encodes it as a revert reason, and your `result` variable contains an already encoded error.
You can still achieve this, but you would have to use inline assembly to return a verbatim copy of the `results` variable. One way to do it is like this:
```sol
// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

contract Caller {
    /// @notice Perform a call - requires CONSIGNOR_CONTROL
    /// @param target Contract to perform the call on
    /// @param data Data to perform the call with
    function call(
        address target,
        bytes calldata data
    )
        external
    {
        (bool ok, bytes memory result) = target.call(data);
        if (!ok) {
            assembly {
                revert(add(32, result), mload(result))
            }
        }
    }
}
```
