### ISSUE TITLE
swapping await - expect sequence produce inconsistent results in test scripts

### ISSUE THREAD

**Issue by nuliknol** [NomicFoundation/hardhat#4813]
### Version of Hardhat

2.19.5

### What happened?

When using the sequence `await expect(method()).to.be.revertedWith()` will miss a revert in a test script.

I am attaching the picture to illustrate the bug. I am also attaching sample project to show the bug. Many test scripts (including the automatic example created by Hardhat itself when initializing the project) first place `await` keyword, then `expect` keyword, but using await before expect may lead to incorrect evaluation of unit tests.

Bug illustration in a github project, just compile and run: https://github.com/nuliknol/await-expect

![bug-explanation](https://github.com/NomicFoundation/hardhat/assets/1125368/d563afd6-37cc-4af8-985e-a283ef8080cd)
[await-expect.tar.gz](https://github.com/NomicFoundation/hardhat/files/14131999/await-expect.tar.gz)

### Minimal reproduction steps

already included

**Comment by fvictorio** [comment]
Hey @nuliknol, I think everything is working as expected. I'll try to explain what's going on here.

First, your `method()` function reverts with a `"You can't run me"` reason string. This means that if you add an assertion for that:

```js
      await expect(sample.method()).to.be.revertedWith("You can't run me");
```

then the test _should_ pass (and it does). You seem to be expecting the test to fail, but that doesn't make sense to me.

The real question is why one of the tests _doesn't_ pass. The reason is that when you do this:

```js
expect(await sample.method()).to.be.revertedWith("You can't run me");
```

the first thing that will be evaluated is `await sample.method()`. But this function returns a rejected promise, because the method reverts. If you await a rejected promise, and error is thrown; if an error is thrown within a test, then the test fails. `await expect(sample.method()`, on the other hand, doesn't await the rejected promise, and it handles it internally, so in that case that's not a problem.

Hopefully that makes sense.
