### ISSUE TITLE
Unify `RESERVED_PARAMETER_NAMES` and `GLOBAL_OPTIONS`

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#5418]
We have two ways to define global builtin options. I think we should unify them, so that most of hardhat can treat the same as user-defined global options.

The one exception would be that some of these built-in global options need to be parsed differently, but it's better to contain that in the parser.

See my [comment](https://github.com/NomicFoundation/hardhat/pull/5409#discussion_r1646657511) here: #5409

**Comment by schaable** [comment]
List of changes:

- [ ] `RESERVED_PARAMETER_NAMES`: update this to be a list of reserved words instead of the current list of built-in options. This list is intended to reserve specific words for future use. The built-in options are already validated by `TaskManager.#validateClashesWithGlobalOptions`.

- [ ] `GLOBAL_OPTIONS`: change this to be an actual array of options, including all their properties, and use `globalOption` to construct them. Also, rename the variable from `GLOBAL_OPTIONS` to `BUILTIN_OPTIONS`, as it only includes the Hardhat built-in options. The logic in `v-next/hardhat/src/internal/cli/helpers/utils.ts` should be updated to reflect this new format.

- [ ] Pass the user-defined global options to `getGlobalHelpString` and print them along with the built-in options.
