### ISSUE TITLE
Warning Messages When Installing Hardhat using npm i hardhat

### ISSUE THREAD

**Issue by Yeasir0032** [NomicFoundation/hardhat#5519]
When attempting to install Hardhat in my project using `npm i hardhat`, the following warning messages were displayed:

```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
```
![image](https://github.com/user-attachments/assets/252ace2a-fc60-4562-83ba-6f788a392d8b)

**Comment by ChristopherDedominici** [comment]
Hi @Yeasir0032, thanks for reporting the issue. 
I created 2 works items to better address these warnings. I'll close this issue because the fix and the additional features will be tracked in these new work items:

1) https://github.com/NomicFoundation/hardhat/issues/5525
2) https://github.com/NomicFoundation/hardhat/issues/5526
