### ISSUE TITLE
Enable debug logging via CLI flag

### ISSUE THREAD

**Issue by zoeyTM** [NomicFoundation/hardhat#5543]
This is a carryover task from #5363 - we want to replicate the Hardhat v2 functionality of enabling debug logging via a CLI flag, but we're unsure at this time exactly what flag that should be. In theory, `--verbose` could work, but there are worries about potentially clashing with other tools.

**Comment by kanej** [comment]
Lets go with `--verbose` as a first pass so that we are only changing a parameter name as part of product polishing.

I think the task here is:

* ENV variable should set config that means we do verbose logging
* optional cli parameter on each of the core tasks should also set that config

Basically, I think we try and avoid setting ENV variables. Though we should check how v2 is doing this.
