### ISSUE TITLE
`changeEtherBalance()` just passes the test with any value

### ISSUE THREAD

**Issue by gkfyr** [NomicFoundation/hardhat#5583]
### Version of Hardhat

2.22.7, 2.12.5, 2.20.1

### What happened?

Hi! I'm working out in my hardhat test codes, using `hardhat-chai-matchers`
but i found the test case just passes with any value if u use `changeEtherBalance()` even it is empty inside.
if u using `changeEtherBalance()`, it passes the it() case with any value or none in `expect()` too.

If u need more detail about this case, I'll gladly help!
Thanks :)

### Minimal reproduction steps

make any test file in the test directory, and run it with `npx hardhat test test/[filename].test.js`

even it appear same in hardhat-boilerplate clone too! https://github.com/NomicFoundation/hardhat-boilerplate

u can see it even passes the test if u put anything or nothing both `expect()` and `changeEtherBalance()`.
```javascript
const { expect } = require("chai");

describe("changeEtherBalance check", function () {
  it("any value", async function () {
    expect().to.changeEtherBalance();
  });
});
```

### Search terms

changeEtherBalance

**Comment by ChristopherDedominici** [comment]
Hi @gkfyr, I reviewed your code and noticed the issue: 
the test is passing because the code isn't waiting for the execution to complete. The `expect().to.changeEtherBalance()` function is asynchronous, so it needs to be awaited. 
If you modify the code to include `await`, like this: 
`await expect().to.changeEtherBalance()` 
the test will fail as expected.

Without `await`, the execution finishes before the `changeEtherBalance` function is executed, resulting in a false positive.
